# -*- coding: UTF-8 -*-

import addonHandler

addonHandler.initTranslation()

Symbols = {
	# Translators: back quote
	_("back quote"): '„',
_("left quote"): '“',
_("right quote"): '”',
_("left tick"): '‘',
_("right tick"): '’',
_("n dash"): '–',
_("m dash"): '—',
_("Aries"): '♈',
_("Taurus"): '♉',
_("Gemini"): '♊',
_("Virgo"): '♍',
_("Libra"): '♎',
_("Scorpio"): '♏',
_("Scorpio"): '♏',
_("Sagittarius"): '♐',
_("Capricorn"): '♑',
_("Aquarius"): '♒',
_("Pisces"): '♓',
_("Leo"): '♌',
_("Check Mark"): '✅',
_("Heart"): '♡',
_("Addition Symbol"): '➕',
_("Square"): '⬛',
_("Square"): '⬜',
_("Star Glyph"): '⭐',
_("Circle"): '⭕',
_("Mahjong"): '🀄',
_("ABO Blood Group System 1"): '🅿',
_("ABO Blood Group System 2"): '🅱',
_("ABO Blood Group System 3"): '🅰',
_("ABO Blood Group System 4"): '🆎',
_("Cool (Aesthetic)"): '🆒',
_("Gratis"): '🆓',
_("Okay"): '🆗',
_("SOS"): '🆘',
_("Apple"): '',
_("Sa (Kana)"): '🈂',
_("Radical 74"): '🈷',
_("Cyclone"): '🌀',
_("Fog"): '🌁',
_("Closed Umbrella"): '🌂',
_("night with stars"): '🌃',
_("sunrise over mountains"): '🌄',
_("Sunrise"): '🌅',
_("Black Square"): '■',
_("Registered"): '♋',
_("cityscape at dusk"): '🌆',
_("sunset over buildings"): '🌇',
_("Rainbow"): '🌈',
_("bridge at night"): '🌉',
_("water wave"): '🌊',
_("INFINITY"): '∞',
_("Volcano"): '🌋',
_("Milkyway"): '🌌',
_("earth globe europe africa"): '🌍',
_("EARTH GLOBE AMERICAS"): '🌎',
_("EARTH GLOBE ASIA AUSTRALIA"): '🌏',
_("GLOBE WITH MERIDIANS"): '🌐',
_("new moon"): '🌑',
_("WAXING CRESCENT MOON"): '🌒',
_("first quarter moon"): '🌓',
_("WAXING GIBBOUS MOON"): '🌔',
_("FULL MOON"): '🌕',
_("WANING GIBBOUS MOON"): '🌖',
_("LAST QUARTER MOON"): '🌗',
_("WANING CRESCENT MOON"): '🌘',
_("CRESCENT MOON"): '🌙',
_("NEW MOON WITH FACE"): '🌚',
_("FIRST QUARTER MOON WITH FACE"): '🌛',
_("LAST QUARTER MOON WITH FACE"): '🌜',
_("FULL MOON WITH FACE"): '🌝',
_("SUN WITH FACE"): '🌞',
_("GLOWING STAR"): '🌟',
_("SHOOTING STAR"): '🌠',
_("CHESTNUT"): '🌰',
_("SEEDLING"): '🌱',
_("EVERGREEN TREE"): '🌲',
_("DECIDUOUS TREE"): '🌳',
_("PALM TREE"): '🌴',
_("CACTUS"): '🌵',
_("TULIP"): '🌷',
_("CHERRY BLOSSOM"): '🌸',
_("HIBISCUS"): '🌺',
_("ROSE"): '🌹',
_("SUNFLOWER"): '🌻',
_("BLOSSOM"): '🌼',
_("EAR OF MAIZE"): '🌽',
_("EAR OF RICE"): '🌾',
_("HERB"): '🌿',
_("FOUR LEAF CLOVER"): '🍀',
_("MAPLE LEAF"): '🍁',
_("FALLEN LEAF"): '🍂',
_("LEAF FLUTTERING IN WIND"): '🍃',
_("MUSHROOM"): '🍄',
_("TOMATO"): '🍅',
_("AUBERGINE"): '🍆',
_("GRAPES"): '🍇',
_("MELON"): '🍈',
_("WATERMELON"): '🍉',
_("TANGERINE"): '🍊',
_("LEMON"): '🍋',
_("BANANA"): '🍌',
_("PINEAPPLE"): '🍍',
_("RED APPLE"): '🍎',
_("GREEN APPLE"): '🍏',
_("PEAR"): '🍐',
_("PEACH"): '🍑',
_("CHERRIES"): '🍒',
_("STRAWBERRY"): '🍓',
_("HAMBURGER"): '🍔',
_("PIZZA SLICE"): '🍕',
_("MEAT ON BONE"): '🍖',
_("POULTRY LEG"): '🍗',
_("RICE CRACKER"): '🍘',
_("RICE BALL"): '🍙',
_("COOKED RICE"): '🍚',
_("CURRY AND RICE"): '🍛',
_("STEAMING BOWL"): '🍜',
_("SPAGHETTI"): '🍝',
_("BREAD"): '🍞',
_("FRENCH FRIES"): '🍟',
_("ROASTED SWEET POTATO"): '🍠',
_("DANGO"): '🍡',
_("ODEN"): '🍢',
_("SUSHI"): '🍣',
_("FRIED SHRIMP"): '🍤',
_("FISH CAKE WITH SWIRL DESIGN"): '🍥',
_("SOFT ICE CREAM"): '🍦',
_("SHAVED ICE"): '🍧',
_("ICE CREAM"): '🍨',
_("DOUGHNUT"): '🍩',
_("COOKIE"): '🍪',
_("CHOCOLATE BAR"): '🍫',
_("CANDY"): '🍬',
_("LOLLIPOP"): '🍭',
_("HONEY"): '🍯',
_("CUSTARD"): '🍮',
_("SHORTCAKE"): '🍰',
_("BENTO BOX"): '🍱',
_("POT OF FOOD"): '🍲',
_("COOKING"): '🍳',
_("FORK AND KNIFE"): '🍴',
_("TEACUP WITHOUT HANDLE"): '🍵',
_("SAKE BOTTLE AND CUP"): '🍶',
_("WINE GLASS"): '🍷',
_("COCKTAIL GLASS"): '🍸',
_("TROPICAL DRINK"): '🍹',
_("BEER MUG"): '🍺',
_("CLINKING BEER MUGS"): '🍻',
_(""): '',
_("BABY BOTTLE"): '🍼',
_("RIBBON"): '🎀',
_("WRAPPED PRESENT"): '🎁',
_("BIRTHDAY CAKE"): '🎂',
_("JACK-O-LANTERN"): '🎃',
_("CHRISTMAS TREE"): '🎄',
_("FATHER CHRISTMAS"): '🎅',
_("FIREWORKS"): '🎆',
_("FIREWORK SPARKLER"): '🎇',
_("BALLOON"): '🎈',
_("PARTY POPPER"): '🎉',
_("CONFETTI BALL"): '🎊',
_("TANABATA TREE"): '🎋',
_("CROSSED FLAGS"): '🎌',
_("PINE DECORATION"): '🎍',
_("JAPANESE DOLLS"): '🎎',
_("CARP STREAMER"): '🎏',
_("WIND CHIME"): '🎐',
_("MOON VIEWING CEREMONY"): '🎑',
_("SCHOOL SATCHEL"): '🎒',
_("GRADUATION CAP"): '🎓',
_("CAROUSEL HORSE"): '🎠',
_("FERRIS WHEEL"): '🎡',
_("ROLLER COASTER"): '🎢',
_("FISHING POLE AND FISH"): '🎣',
_("MICROPHONE"): '🎤',
_("MOVIE CAMERA"): '🎥',
_("CINEMA"): '🎦',
_("HEADPHONE"): '🎧',
_(""): '',
_("ARTIST PALETTE"): '🎨',
_("CIRCUS TENT"): '🎪',
_("TOP HAT"): '🎩',
_("TICKET"): '🎫',
_("CLAPPER BOARD"): '🎬',
_("PERFORMING ARTS"): '🎭',
_("VIDEO GAME"): '🎮',
_("DIRECT HIT"): '🎯',
_("SLOT MACHINE"): '🎰',
_("BILLIARDS"): '🎱',
_("GAME DIE"): '🎲',
_("BOWLING"): '🎳',
_("FLOWER PLAYING CARDS"): '🎴',
_(""): '',
_("MUSICAL NOTE"): '🎵',
_("MULTIPLE MUSICAL NOTES"): '🎶',
_("SAXOPHONE"): '🎷',
_("GUITAR"): '🎸',
_("MUSICAL KEYBOARD"): '🎹',
_("TRUMPET"): '🎺',
_("VIOLIN"): '🎻',
_("MUSICAL SCORE"): '🎼',
_("RUNNING SHIRT WITH SASH"): '🎽',
_("TENNIS RACQUET AND BALL"): '🎾',
_("SKI AND SKI BOOT"): '🎿',
_("BASKETBALL AND HOOP"): '🏀',
_("CHEQUERED FLAG"): '🏁',
_("SNOWBOARDER"): '🏂',
_("RUNNER"): '🏃',
_("SURFER"): '🏄',
_("TROPHY"): '🏆',
_("HORSE RACING"): '🏇',
_("AMERICAN FOOTBALL"): '🏈',
_("RUGBY FOOTBALL"): '🏉',
_("SWIMMER"): '🏊',
_("HOUSE BUILDING"): '🏠',
_("HOUSE WITH GARDEN"): '🏡',
_("OFFICE BUILDING"): '🏢',
_("JAPANESE POST OFFICE"): '🏣',
_("EUROPEAN POST OFFICE"): '🏤',
_("HOSPITAL"): '🏥',
_("BANK"): '🏦',
_("AUTOMATED TELLER MACHINE"): '🏧',
_("HOTEL"): '🏨',
_("LOVE HOTEL"): '🏩',
_("CONVENIENCE STORE"): '🏪',
_("SCHOOL"): '🏫',
_("DEPARTMENT STORE"): '🏬',
_(""): '',
_("FACTORY"): '🏭',
_("IZAKAYA LANTERN"): '🏮',
_("JAPANESE CASTLE"): '🏯',
_("EUROPEAN CASTLE"): '🏰',
_("RAT"): '🐀',
_("MOUSE"): '🐁',
_("OX"): '🐂',
_("WATER BUFFALO"): '🐃',
_("COW"): '🐄',
_("TIGER"): '🐅',
_("LEOPARD"): '🐆',
_("RABBIT"): '🐇',
_("CAT"): '🐈',
_("DRAGON"): '🐉',
_("CROCODILE"): '🐊',
_("WHALE"): '🐋',
_("SNAIL"): '🐌',
_("SNAKE"): '🐍',
_("HORSE"): '🐎',
_("RAM"): '🐏',
_("GOAT"): '🐐',
_("SHEEP"): '🐑',
_("MONKEY"): '🐒',
_("ROOSTER"): '🐓',
_("CHICKEN"): '🐔',
_("DOG"): '🐕',
_("PIG"): '🐖',
_("BOAR"): '🐗',
_("ELEPHANT"): '🐘',
_("OCTOPUS"): '🐙',
_("SPIRAL SHELL"): '🐚',
_("BUG"): '🐛',
_("ANT"): '🐜',
_("HONEYBEE"): '🐝',
_("LADY BEETLE"): '🐞',
_("FISH"): '🐟',
_("TROPICAL FISH"): '🐠',
_("BLOWFISH"): '🐡',
_("TURTLE"): '🐢',
_("HATCHING CHICK"): '🐣',
_("BABY CHICK"): '🐤',
_("FRONT-FACING BABY CHICK"): '🐥',
_("BIRD"): '🐦',
_("PENGUIN"): '🐧',
_("KOALA"): '🐨',
_("POODLE"): '🐩',
_("DROMEDARY CAMEL"): '🐪',
_("BACTRIAN CAMEL"): '🐫',
_("DOLPHIN"): '🐬',
_("MOUSE FACE"): '🐭',
_("COW FACE"): '🐮',
_("TIGER FACE"): '🐯',
_("RABBIT FACE"): '🐰',
_("CAT FACE"): '🐱',
_("DRAGON FACE"): '🐲',
_("SPOUTING WHALE"): '🐳',
_("HORSE FACE"): '🐴',
_("MONKEY FACE"): '🐵',
_("DOG FACE"): '🐶',
_("PIG FACE"): '🐷',
_("FROG FACE"): '🐸',
_("HAMSTER FACE"): '🐹',
_("WOLF FACE"): '🐺',
_("BEAR FACE"): '🐻',
_("PANDA FACE"): '🐼',
_("PIG NOSE"): '🐽	',
_("PAW PRINTS"): '🐾',
_("EYES"): '👀',
_("EAR"): '👂',
_("NOSE"): '👃',
_("MOUTH"): '👄',
_("TONGUE"): '👅',
_("WHITE UP POINTING BACKHAND INDEX"): '👆',
_("WHITE DOWN POINTING BACKHAND INDEX"): '👇',
_("WHITE LEFT POINTING BACKHAND INDEX"): '👈',
_("WHITE RIGHT POINTING BACKHAND INDEX"): '👉',
_("FISTED HAND SIGN"): '👊',
_("WAVING HAND SIGN"): '👋',
_("OK HAND SIGN"): '👌',
_("THUMBS DOWN"): '👎',
_("THUMBS UP"): '👍',
_("CLAPPING HANDS SIGN"): '👏',
_("OPEN HANDS SIGN"): '👐',
_("CROWN"): '👑',
_("WOMANS HAT"): '👒',
_("EYEGLASSES"): '👓',
_("NECK TIE"): '👔',
_("T SHIRT"): '👕',
_("JEANS"): '👖',
_("DRESS"): '👗',
_("KIMONO"): '👘',
_("BIKINI"): '👙',
_("WOMANS CLOTHES"): '👚',
_(""): '',
_("PURSE"): '👛',
_("HANDBAG"): '👜',
_("POUCH"): '👝',
_("MANS SHOE"): '👞',
_("ATHLETIC SHOE"): '👟',
_("HIGH-HEALED SHOE"): '👠',
_("WOMANS SANDAL"): '👡',
_("WOMANS BOOTS"): '👢',
_("FOOTPRINTS"): '👣',
_("BUST IN SILHOUETTE"): '👤',
_("BUSTS IN SILHOUETTE"): '👥',
_("BOY"): '👦',
_("GIRL"): '👧',
_("MAN"): '👨',
_("WOMAN"): '👩',
_("FAMILY"): '👪',
_("MAN AND WOMAN HOLDING HANDS"): '👫',
_("TWO MEN HOLDING HANDS"): '👬',
_("TWO WOMEN HOLDING HANDS"): '👭',
_("POLICE OFFICER"): '👮',
_("WOMAN WITH BUNNY EARS"): '👯',
_("BRIDE WITH VEIL"): '👰',
_("PERSON WITH BLOND HAIR"): '👱',
_("MAN WITH GUA PI MAO"): '👲',
_("MAN WITH TURBAN"): '👳',
_("OLDER MAN"): '👴',
_("OLDER WOMAN"): '👵',
_("BABY"): '👶',
_("CONSTRUCTION WORKER"): '👷',
_("PRINCESS"): '👸',
_("JAPANESE OGRE"): '👹',
_("JAPANESE GOBLIN"): '👺',
_("GHOST"): '👻',
_("BABY ANGEL"): '👼',
_("EXTRATERRESTRIAL ALIEN"): '👽',
_("ALIEN MONSTER"): '👾',
_("IMP"): '👿',
_("SKULL"): '💀',
_("INFORMATION DESK PERSON"): '💁',
_("GUARDSMAN"): '💂',
_("DANCER"): '💃',
_("LIPSTICK"): '💄',
_("NAIL POLISH"): '💅',
_("FACE MASSAGE"): '💆',
_("HAIRCUT"): '💇',
_("BARBER POLL"): '💈',
_("SYRINGE"): '💉',
_("PILL"): '💊',
_("KISS MARK"): '💋',
_("LOVE LETTER"): '💌',
_("RING"): '💍',
_("GEM STONE"): '💎',
_("KISS"): '💏',
_("BOUQUET"): '💐',
_("COUPLE WITH HEART"): '💑',
_("WEDDING"): '💒',
_("BEATING HEART"): '💓',
_("BROKEN HEART"): '💔',
_("TWO HEARTS"): '💕',
_("SPARKLING HEART"): '💖',
_("GROWING HEART"): '💗',
_("HEART WITH ARROW"): '💘',
_("BLUE HEART"): '💙',
_("GREEN HEART"): '💚',
_("YELLOW HEART"): '💛',
_("PURPLE HEART"): '💜',
_("HEART WITH RIBBON"): '💝',
_("REVOLVING HEARTS"): '💞',
_("HEART DECORATION"): '💟',
_("DIAMOND SHAPE WITH A DOT INSIDE"): '💠',
_("ELECTRIC LIGHT BULB"): '💡',
_("ANGER SYMBOL"): '💢',
_("BOMB"): '💣',
_("SLEEPING SYMBOL"): '💤',
_("COLLISION SYMBOL"): '💥',
_("SPLASHING SWEAT SYMBOL"): '💦',
_("DROPLET"): '💧',
_("DASH SYMBOL"): '💨',
_("PILE OF POO"): '💩',
_("FLEXED BICEPS"): '💪',
_("DIZZY SYMBOL"): '💫',
_("SPEECH BALLOON"): '💬',
_("THOUGHT BALLOON"): '💭',
_("WHITE FLOWER"): '💮',
_("HUNDRED POINTS SYMBOL"): '💯',
_("MONEY BAG"): '💰',
_("CURRENCY EXCHANGE"): '💱',
_("HEAVY DOLLAR SIGN"): '💲',
_("CREDIT CARD"): '💳',
_("BANKNOTE WITH YEN SIGN"): '💴',
_("BANKNOTE WITH DOLLAR SIGN"): '💵',
_("BANKNOTE WITH EURO SIGN"): '💶',
_("BANKNOTE WITH POUND SIGN"): '💷',
_("MONEY WITH WINGS"): '💸',
_("CHART WITH UPWARDS TREND"): '💹',
_("SEAT"): '💺',
_("PERSONAL COMPUTER"): '💻',
_("BRIEFCASE"): '💼',
_("MINIDISC"): '💽',
_("FLOPPY DISK"): '💾',
_("OPTICAL DISC"): '💿',
_("DVD"): '📀',
_("FILE FOLDER"): '📁',
_("OPEN FILE FOLDER"): '📂',
_("PAGE WITH CURL"): '📃',
_("PAGE FACING UP"): '📄',
_("CALENDAR"): '📅',
_("TEAR-OFF CALENDAR"): '📆',
_("CARD INDEX"): '📇',
_("CHART WITH UPWARDS TREND"): '📈',
_("CHART WITH DOWNWARDS TREND"): '📉',
_("BAR CHART"): '📊',
_("CLIPBOARD"): '📋',
_("PUSHPIN"): '📌',
_("ROUND PUSHPIN"): '📍',
_("PAPER CLIP"): '📎',
_("STRAIGHT RULER"): '📏',
_("TRIANGULAR RULER"): '📐',
_("BOOKMARK TABS"): '📑',
_("LEDGER"): '📒',
_("NOTEBOOK"): '📓',
_("NOTEBOOK WITH DECORATIVE COVER"): '📔',
_("CLOSED BOOK"): '📕',
_("OPEN BOOK"): '📖',
_("GREEN BOOK"): '📗',
_("BLUE BOOK"): '📘',
_("ORANGE BOOK"): '📙',
_("BOOKS"): '📚',
_("NAME BADGE"): '📛',
_("CAMERA"): '📷',
_("VIDEO CAMERA"): '📹',
_("TELEVISION"): '📺',
_("RADIO"): '📻',
_("VIDEO CASSETTE"): '📼',
_("TWISTED RIGHTWARDS ARROWS"): '🔀',
_("CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS"): '🔁',
_("CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY"): '🔂',
_("CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS"): '🔃',
_("ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS"): '🔄',
_("LOW BRIGHTNESS SYMBOL"): '🔅',
_("HIGH BRIGHTNESS SYMBOL"): '🔆',
_("SPEAKER WITH CANCELLATION STROKE"): '🔇',
_("SPEAKER"): '🔈',
_("SPEAKER WITH ONE SOUND WAVE"): '🔉',
_("SPEAKER WITH THREE SOUND WAVES"): '🔊',
_("BATTERY"): '🔋',
_("ELECTRIC PLUG"): '🔌',
_("LEFT POINTING MAGNIFYING GLASS"): '🔍',
_("RIGHT POINTING MAGNIFYING GLASS"): '🔎',
_("LOCK WITH INK PEN"): '🔏',
_("CLOSED LOCK WITH KEY"): '🔐',
_("KEY"): '🔑',
_("LOCK"): '🔒',
_("OPEN LOCK"): '🔓',
_("BELL"): '🔔',
_("BELL WITH CANCELLATION STROKE"): '🔕',
_(""): '',
_("BOOKMARK"): '🔖',
_("LINK SYMBOL"): '🔗',
_("RADIO BUTTON"): '🔘',
_("UP POINTING RED TRIANGLE"): '🔺',
_("DOWN POINTING RED TRIANGLE"): '🔻',
_("UP POINTING SMALL RED TRIANGLE"): '🔼',
_("DOWN POINTING SMALL RED TRIANGLE"): '🔽',
_("BACK WITH LEFTWARDS ARROW ABOVE"): '🔙',
_("END WITH LEFTWARDS ARROW ABOVE"): '🔚',
_("ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE"): '🔛',
_("SOON WITH RIGHTWARDS ARROW ABOVE"): '🔜',
_("TOP WITH UPWARDS ARROW ABOVE"): '🔝',
_("NO ONE UNDER 18 SYMBOL"): '🔞',
_("KEYCAP 10"): '🔟',
_("INPUT SYMBOL FOR LATIN CAPITAL LETTERS"): '🔠',
_("INPUT SYMBOL FOR LATIN SMALL LETTERS"): '🔡',
_("INPUT SYMBOL FOR NUMBERS"): '🔢',
_("INPUT SYMBOL FOR SYMBOLS"): '🔣',
_("INPUT SYMBOL FOR LATIN LETTERS"): '🔤',
_("FIRE"): '🔥',
_("ELECTRIC TORCH"): '🔦',
_("WRENCH"): '🔧',
_("HAMMER"): '🔨',
_("NUT AND BOLT"): '🔩',
_("HOCHO"): '🔪',
_("PISTOL"): '🔫',
_("MICROSCOPE"): '🔬',
_("TELESCOPE"): '🔭',
_("CRYSTAL BALL"): '🔮',
_("SIX POINTED STAR WITH MIDDLE DOT"): '🔯',
_("JAPANESE SYMBOL FOR BEGINNER"): '🔰',
_("TRIDENT EMBLEM"): '🔱',
_("BLACK SQUARE BUTTON"): '🔲',
_("WHITE SQUARE BUTTON"): '🔳',
_("LARGE RED CIRCLE"): '🔴',
_("LARGE BLUE CIRCLE"): '🔵',
_("LARGE ORANGE DIAMOND"): '🔶',
_("LARGE BLUE DIAMOND"): '🔷',
_("SMALL ORANGE DIAMOND"): '🔸',
_("SMALL BLUE DIAMOND"): '🔹',
_("CIRCLED CROSS POMMEE"): '🕀',
_("CROSS POMMEE WITH HALF CIRCLE BELOW"): '🕁',
_("CROSS POMMEE"): '🕂',
_("NOTCHED LEFT SEMICIRCLE WITH THREE DOTS"): '🕃',
_("CLOCK FACE ONE OCLOCK"): '🕐',
_("CLOCK FACE TWO OCLOCK"): '🕑',
_("CLOCK FACE THREE OCLOCK"): '🕒',
_("CLOCK FACE FOUR OCLOCK"): '🕓',
_("CLOCK FACE FIVE OCLOCK"): '🕔',
_("CLOCK FACE SIX OCLOCK"): '🕕',
_("CLOCK FACE SEVEN OCLOCK"): '🕖',
_("CLOCK FACE EIGHT OCLOCK"): '🕗',
_("CLOCK FACE NINE OCLOCK"): '🕘',
_("CLOCK FACE TEN OCLOCK"): '🕙',
_("CLOCK FACE ELEVEN OCLOCK"): '🕚',
_("CLOCK FACE TWELVE OCLOCK"): '🕛',
_("CLOCK FACE ONE THIRTY"): '🕜',
_("CLOCK FACE TWO THIRTY"): '🕝',
_("CLOCK FACE THREE THIRTY"): '🕞',
_("CLOCK FACE FOUR THIRTY"): '🕟',
_("CLOCK FACE FIVE THIRTY"): '🕠',
_("CLOCK FACE SIX THIRTY"): '🕡',
_("CLOCK FACE SEVEN THIRTY"): '🕢',
_("CLOCK FACE EIGHT THIRTY"): '🕣',
_("CLOCK FACE NINE THIRTY"): '🕤',
_("CLOCK FACE TEN THIRTY"): '🕥',
_("CLOCK FACE ELEVEN THIRTY"): '🕦',
_("CLOCK FACE TWELVE THIRTY"): '🕧',
_("MOUNT FUJI"): '🗻',
_("TOKYO TOWER"): '🗼',
_("STATUE OF LIBERTY"): '🗽',
_("SILHOUETTE OF JAPAN"): '🗾',
_("MOYAI"): '🗿',
_("WHITE SQUARE"): '□',
_("WHITE SQUARE WITH ROUNDED CORNERS"): '▢',
_("WHITE SQUARE CONTAINING BLACK SMALL SQUARE"): '▣',
_("SQUARE WITH HORIZONTAL FILL"): '▤',
_("SQUARE WITH VERTICAL FILL"): '▥',
_("SQUARE WITH ORTHOGONAL CROSSHATCH FILL"): '▦',
_("SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL"): '▧',
_("SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL"): '▨',
_("SQUARE WITH DIAGONAL CROSSHATCH FILL"): '▩',
_("BLACK SMALL SQUARE"): '▪',
_("WHITE SMALL SQUARE"): '▫',
_("BLACK RECTANGLE"): '▬',
_("WHITE RECTANGLE"): '▭',
_("BLACK VERTICAL RECTANGLE"): '▮',
_("BLACK VERTICAL RECTANGLE"): '▯',
_("BLACK PARALLELOGRAM"): '▰',
_("WHITE PARALLELOGRAM"): '▱',
_("BLACK UP-POINTING TRIANGLE"): '▲',
_("WHITE UP-POINTING TRIANGLE"): '△',
_("BLACK UP-POINTING SMALL TRIANGLE"): '▴',
_("WHITE UP-POINTING SMALL TRIANGLE"): '▵',
_("BLACK RIGHT-POINTING TRIANGLE"): '▶',
_("WHITE RIGHT-POINTING TRIANGLE"): '▷',
_("BLACK RIGHT-POINTING SMALL TRIANGLE"): '▸',
_("WHITE RIGHT-POINTING SMALL TRIANGLE"): '▹',
_("BLACK RIGHT-POINTING POINTER"): '►',
_("BLACK DOWN-POINTING TRIANGLE"): '▼',
_("WHITE RIGHT-POINTING POINTER"): '▻',
_("WHITE DOWN-POINTING TRIANGLE"): '▽',
_("BLACK DOWN-POINTING SMALL TRIANGLE"): '▾',
_("WHITE DOWN-POINTING SMALL TRIANGLE"): '▿',
_("BLACK LEFT-POINTING TRIANGLE"): '◀',
_("WHITE LEFT-POINTING TRIANGLE"): '◁',
_("BLACK LEFT-POINTING SMALL TRIANGLE"): '◂',
_("WHITE LEFT-POINTING SMALL TRIANGLE"): '◃',
_("BLACK LEFT-POINTING POINTER"): '◄',
_("WHITE LEFT-POINTING POINTER"): '◅',
_("BLACK DIAMOND"): '◆',
_("WHITE DIAMOND"): '◇',
_("WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND"): '◈',
_("FISH EYE"): '◉',
_("LOZENGE"): '◊',
_("WHITE CIRCLE"): '○',
_("DOTTED CIRCLE"): '◌',
_("CIRCLE WITH VERTICAL FILL"): '◍',
_("BULLSEYE"): '◎',
_("BLACK CIRCLE"): '●',
_("CIRCLE WITH LEFT HALF BLACK"): '◐',
_("CIRCLE WITH RIGHT HALF BLACK"): '◑',
_("CIRCLE WITH LOWER HALF BLACK"): '◒',
_("CIRCLE WITH UPPER HALF BLACK"): '◓',
_("CIRCLE WITH UPPER RIGHT QUADRANT BLACK"): '◔',
_("CIRCLE WITH ALL BUT UPPER LEFT QUADRANT BLACK"): '◕',
_("LEFT HALF BLACK CIRCLE"): '◖',
_("RIGHT HALF BLACK CIRCLE"): '◗',
_("INVERSE WHITE CIRCLE"): '◙',
_("INVERSE BULLET"): '◘',
_("UPPER HALF INVERSE WHITE CIRCLE"): '◚',
_("LOWER HALF INVERSE WHITE CIRCLE"): '◛',
_("UPPER LEFT QUADRANT CIRCULAR ARC"): '◜',
_("UPPER RIGHT QUADRANT CIRCULAR ARC"): '◝',
_("LOWER RIGHT QUADRANT CIRCULAR ARC"): '◞',
_("LOWER LEFT QUADRANT CIRCULAR ARC"): '◟',
_("UPPER HALF CIRCLE"): '◠',
_("LOWER HALF CIRCLE"): '◡',
_("BLACK LOWER RIGHT TRIANGLE"): '◢',
_("BLACK LOWER LEFT TRIANGLE"): '◣',
_("BLACK UPPER LEFT TRIANGLE"): '◤',
_("BLACK UPPER RIGHT TRIANGLE"): '◥',
_("WHITE BULLET"): '◦',
_("SQUARE WITH LEFT HALF BLACK"): '◧',
_("SQUARE WITH RIGHT HALF BLACK"): '◨',
_("SQUARE WITH UPPER LEFT DIAGONAL HALF BLACK"): '◩',
_("SQUARE WITH LOWER RIGHT DIAGONAL HALF BLACK"): '◪',
_("WHITE SQUARE WITH VERTICAL BISECTING LINE"): '◫',
_("WHITE UP-POINTING TRIANGLE WITH DOT"): '◬',
_("UP-POINTING TRIANGLE WITH LEFT HALF BLACK"): '◭',
_("UP-POINTING TRIANGLE WITH RIGHT HALF BLACK"): '◮',
_("LARGE CIRCLE"): '◯',
_("UPPER LEFT TRIANGLE"): '◸',
_("UPPER RIGHT TRIANGLE"): '◹',
_("LOWER LEFT TRIANGLE"): '◺',
_("WHITE MEDIUM SQUARE"): '◻',
_("BLACK MEDIUM SQUARE"): '◼',
_("WHITE MEDIUM SMALL SQUARE"): '◽',
_("BLACK MEDIUM SMALL SQUARE"): '◾',
_("LOWER RIGHT TRIANGLE"): '◿',
_("WHITE SQUARE WITH UPPER LEFT QUADRANT"): '◰',
_("WHITE SQUARE WITH LOWER LEFT QUADRANT"): '◱',
_("WHITE SQUARE WITH LOWER RIGHT QUADRANT"): '◲',
_("WHITE SQUARE WITH UPPER RIGHT QUADRANT"): '◳',
_("WHITE CIRCLE WITH UPPER LEFT QUADRANT"): '◴',
_("WHITE CIRCLE WITH LOWER LEFT QUADRANT"): '◵',
_("WHITE CIRCLE WITH LOWER RIGHT QUADRANT"): '◶',
_("WHITE CIRCLE WITH UPPER RIGHT QUADRANT"): '◷',
_("GRINNING FACE"): '😀',
_("GRINNING FACE WITH SMILING EYES"): '😁',
_("FACE WITH TEARS OF JOY"): '😂',
_("SMILING FACE WITH OPEN MOUTH"): '😃',
_("SMILING FACE WITH OPEN MOUTH AND SMILING EYES"): '😄',
_("SMILING FACE WITH OPEN MOUTH AND COLD SWEAT"): '😅',
_("SMILING FACE WITH OPEN MOUTH AND TIGHTLY CLOSED EYES"): '😆',
_("SMILING FACE WITH HALO"): '😇',
_("SMILING FACE WITH HORNS"): '😈',
_("WINKING FACE"): '😉',
_("SMILING FACE WITH SMILING EYES"): '😊',
_("FACE SAVOURING DELICIOUS FOOD"): '😋',
_("RELIEVED FACE"): '😌',
_("SMILING FACE WITH HEART SHAPED EYES"): '😍',
_("SMILING FACE WITH SUNGLASSES"): '😎',
_("SMIRKING FACE"): '😏',
_("NEUTRAL FACE"): '😐',
_("EXPRESSIONLESS FACE"): '😑',
_("UNAMUSED FACE"): '😒',
_("FACE WITH COLD SWEAT"): '😓',
_("PENSIVE FACE"): '😔',
_("CONFUSED FACE"): '😕',
_("CONFOUNDED FACE"): '😖',
_("KISSING FACE"): '😗',
_("FACE THROWING A KISS"): '😘',
_("KISSING FACE WITH SMILING EYES"): '😙',
_("KISSING FACE WITH CLOSED EYES"): '😚',
_("FACE WITH STUCK OUT TONGUE"): '😛',
_("FACE WITH STUCK OUT TONGUE AND WINKING EYE"): '😜',
_("FACE WITH STUCK OUT TONGUE AND TIGHTLY CLOSED EYES"): '😝',
_("DISAPPOINTED FACE"): '😞',
_("WORRIED FACE"): '😟',
_("ANGRY FACE"): '😠',
_("POUTING FACE"): '😡',
_("CRYING FACE"): '😢',
_("PERSEVERING FACE"): '😣',
_("Triumphant face"): '😤',
_("DISAPPOINTED BUT RELIEVED FACE"): '😥',
_("FROWNING FACE WITH OPEN MOUTH"): '😦',
_("ANGUISHED FACE"): '😧',
_("FEARFUL FACE"): '😨',
_("WEARY FACE"): '😩',
_("SLEEPY FACE"): '😪',
_("TIRED FACE"): '😫',
_("GRIMACING FACE"): '😬',
_("LOUDLY CRYING FACE"): '😭',
_("FACE WITH OPEN MOUTH"): '😮',
_("HUSHED FACE"): '😯',
_("FACE WITH OPEN MOUTH AND COLD SWEAT"): '😰',
_("FACE SCREAMING IN FEAR"): '😱',
_("ASTONISHED FACE"): '😲',
_("FLUSHED FACE"): '😳',
_("SLEEPING FACE"): '😴',
_("DIZZY FACE"): '😵',
_("FACE WITHOUT MOUTH"): '😶',
_("FACE WITH MEDICAL MASK"): '😷',
_("GRINNING CAT FACE WITH SMILING EYES"): '😸',
_("CAT FACE WITH TEARS OF JOY"): '😹',
_("SMILING CAT FACE WITH OPEN MOUTH"): '😺',
_("SMILING CAT FACE WITH HEART SHAPED EYES"): '😻',
_("CAT FACE WITH WRY SMILE"): '😼',
_("KISSING CAT FACE WITH CLOSED EYES"): '😽',
_("POUTING CAT FACE"): '😾',
_("CRYING CAT FACE"): '😿',
_("WEARY CAT FACE"): '🙀',
_("FACE WITH NO GOOD GESTURE"): '🙅',
_("FACE WITH OK GESTURE"): '🙆',
_("PERSON BOWING DEEPLY"): '🙇',
_("SEE NO EVIL MONKEY"): '🙈',
_("HEAR NO EVIL MONKEY"): '🙉',
_("SPEAK NO EVIL MONKEY"): '🙊',
_("HAPPY PERSON RAISING ONE HAND"): '🙋',
_("PERSON RAISING BOTH HANDS IN CELEBRATION"): '🙌',
_("PERSON FROWNING"): '🙍',
_("PERSON WITH POUTING FACE"): '🙎',
_("PERSON WITH FOLDED HANDS"): '🙏',
_("ROCKET"): '🚀',
_("HELICOPTER"): '🚁',
_("STEAM LOCOMOTIVE"): '🚂',
_("RAILWAY CAR"): '🚃',
_("HIGH-SPEED TRAIN"): '🚄',
_("HIGH-SPEED TRAIN WITH BULLET NOSE"): '🚅',
_("TRAIN"): '🚆',
_("METRO"): '🚇',
_("LIGHT RAIL"): '🚈',
_("STATION"): '🚉',
_("TRAM"): '🚊',
_("TRAM CAR"): '🚋',
_("BUS"): '🚌',
_("ONCOMING BUS"): '🚍',
_("TROLLEYBUS"): '🚎',
_("BUS STOP"): '🚏',
_("MINIBUS"): '🚐',
_("AMBULANCE"): '🚑',
_("One-Way Traffic"): '⛔',
_("CHURCH BUILDING"): '⛪',
_("FIRE ENGINE"): '🚒',
_("POLICE CAR"): '🚓',
_("ONCOMING POLICE CAR"): '🚔',
_("TAXI"): '🚕',
_("ONCOMING TAXI"): '🚖',
_("AUTOMOBILE"): '🚗',
_("ONCOMING AUTOMOBILE"): '🚘',
_("RECREATIONAL VEHICLE"): '🚙',
_("DELIVERY TRUCK"): '🚚',
_("ARTICULATED LORRY"): '🚛',
_("Tractor"): '🚜',
_("MONORAIL"): '🚝',
_("MOUNTAIN RAILWAY"): '🚞',
_("SUSPENSION RAILWAY"): '🚟',
_("MOUNTAIN CABLEWAY"): '🚠',
_("AERIAL TRAMWAY"): '🚡',
_("SHIP"): '🚢',
_("ROWBOAT"): '🚣',
_("SPEED BOAT"): '🚤',
_("HORIZONTAL TRAFFIC LIGHT"): '🚥',
_("VERTICAL TRAFFIC LIGHT"): '🚦',
_("CONSTRUCTION SIGN"): '🚧',
_("POLICE CARS REVOLVING LIGHT"): '🚨',
_("TRIANGULAR FLAG ON POST"): '🚩',
_("DOOR"): '🚪',
_("NO ENTRY SIGN"): '🚫',
_("SMOKING SIGN"): '🚬',
_("NO SMOKING SIGN"): '🚭',
_("PUT LITTER IN ITS PLACE SIGN"): '🚮',
_("DO NOT LITTER SIGN"): '🚯',
_("POTABLE WATER SIGN"): '🚰',
_("NON POTABLE WATER SIGN"): '🚱',
_("BICYCLE"): '🚲',
_("NO BICYCLES"): '🚳',
_("BICYCLIST"): '🚴',
_("MOUNTAIN BICYCLIST"): '🚵',
_("PEDESTRIAN"): '🚶',
_("NO PEDESTRIANS"): '🚷',
_("CHILDREN CROSSING"): '🚸',
_("MENS SYMBOL"): '🚹',
_("WOMENS SYMBOL"): '🚺',
_("RESTROOM"): '🚻',
_("BABY"): '🚼',
_("TOILET"): '🚽',
_("WATER CLOSET"): '🚾',
_("SHOWER"): '🚿',
_("BATH"): '🛀',
_("BATHTUB"): '🛁',
_("PASSPORT CONTROL"): '🛂',
_("CUSTOMS"): '🛃',
_("BAGGAGE CLAIM"): '🛄',
_("LEFT LUGGAGE"): '🛅',
_("BLACK SMILING FACE"): '☻',
_("WHITE FROWNING FACE"): '☹',
_("WHITE SMILING FACE"): '☺',
_("First Quarter Moon"): '☽',
_("Last Quarter Moon"): '☾',
_("Mercury"): '☿',
_("Female or Venus"): '♀',
_("Earth"): '♁',
_("Male or Mars"): '♂',
_("Jupiter"): '♃',
_("Saturn"): '♄',
_("Uranus"): '♅',
_("Neptune"): '♆',
_("Pluto"): '♇',
_("Black Sun With Rays"): '☀',
_("Cloud"): '☁',
_("Umbrella"): '☂',
_("Snowman"): '☃',
_("Comet"): '☄',
_("Black Star"): '★',
_("STAR OPERATOR"): '⋆',
_("White Star"): '☆',
_("stress outlined white star"): '✩',
_("Sun"): '☉',
_("Lightning"): '☇',
_("Thunder Storm"): '☈',
_("Ascending Node"): '☊',
_("Descending Node"): '☋',
_("alchemical symbol for purify"): '🝣',
_("Conjunction"): '☌',
_("Pager"): '📟',
_("Fax"): '📠',
_("Satellite Dish"): '📡',
_("Email"): '📧',
_("Horn Loudspeaker"): '📢',
_("Email"): '📤',
_("Email"): '📥',
_("FACE WITH OPEN MOUTH AND COLD SWEAT"): '😰',
_("Letter Box 1"): '📪',
_("Letter Box 2"): '📫',
_("Megaphone"): '📣',
_("Post Box"): '📮',
_("Post Horn"): '📯',
_("Mobile Phone"): '📱',
_("Silent Mode"): '📳',
_("Mobile Phone Signal"): '📶',
_("Newspaper"): '📰',
_("Letter Box 3"): '📭',
_("Black Telephone"): '☎',
_("Telephone Sign"): '℡',
_("Telephone Location Sign"): '✆',
_("Telephone Receiver"): '📞',
_("White Telephone"): '☏',
_("Ballot Box"): '☐',
_("Ballot Box with Check"): '☑',
_("Ballot  Box with X"): '☒',
_("SQUARED TIMES"): '⊠',
_("SALTIRE"): '☓',
_("BALLOT X"): '✗',
_("Umbrella With Rain Drops"): '☔',
_("Hot Beverage"): '☕',
_("Watch"): '⌚',
_("Hour Glass"): '⌛',
_("Shamrock"): '☘',
_("Reversed Rotated Floral Heart Bullet"): '☙',
_("ROTATED FLORAL HEART BULLET"): '❧',
_("Black Left Pointing Index"): '☚',
_("Black right Pointing Index"): '☛',
_("White Left Pointing Index"): '☜',
_("White Up Pointing Index"): '☝',
_("White Right Pointing Index"): '☞',
_("White Down Pointing Index"): '☟',
_("Skull And Crossbones"): '☠',
_("Caution"): '☡',
_("Radioactive"): '☢',
_("Biohazard Sign"): '☣',
_("Caduceus"): '☤',
_("staff of aesculapius"): '⚕',
_("alchemical symbol for caduceus"): '🝐',
_("Ankh"): '☥',
_("Warning Sign"): '⚠',
_("High Voltage"): '⚡',
_("Orthodox Cross"): '☦',
_("Chi Rho"): '☧',
_("coptic symbol khi ro"): '⳩',
_("Cross Of Lorraine"): '☨',
_("Cross Of Jerusalem"): '☩',
_("alchemical symbol for vinegar"): '🜊',
_("Star And Crescent"): '☪',
_("Farsi Symbol"): '☫',
_("Adi Shakti"): '☬',
_("Hammer And Sickle"): '☭',
_("Peace Symbol"): '☮',
_("Yin Yang"): '☯',
_("Heaven Trigram"): '☰',
_("Lake Trigram"): '☱',
_("Fire Trigram"): '☲',
_("Thunder Trigram"): '☳',
_("Wind Trigram"): '☴',
_("Water Trigram"): '☵',
_("Mountain Trigram"): '☶',
_("Hot Springs"): '♨',
_("Quarter Note"): '♩',
_("Eighth Note"): '♪',
_("Beamed Eighth Notes"): '♫',
_("Beamed Sixteenth Notes"): '♬',
_("Music Flat Sign"): '♭',
_("Music Natural Sign"): '♮',
_("Music Sharp Sign"): '♯',
_("Recycle Sign"): '♲',
_("Recycling Symbol For Type-1 Plastics"): '♳',
_("Recycling Symbol For Type-2 Plastics"): '♴',
_("Recycling Symbol For Type-3 Plastics"): '♵',
_("Recycling Symbol For Type-4 Plastics"): '♶',
_("Recycling Symbol For Type-5 Plastics"): '♷',
_("Recycling Symbol For Type-6 Plastics"): '♸',
_("Recycling Symbol For Type-7 Plastics"): '♹',
_("Recycling for generic materials"): '♺',
_("Black Universal Recycling Symbol"): '♻',
_("Recycled Paper Symbol"): '♼',
_("Partial Recycled Paper Symbol"): '♽',
_("Permanent Paper Sign"): '♾',
_("Wheelchair"): '♿',
_("White Flag"): '⚐',
_("Flag of China"): '🇨🇳',
_("Flag of South Korea"): '🇰🇷',
_("Flag of Germany"): '🇩🇪',
_("Flag of France"): '🇫🇷',
_("Flag of the United States"): '🇺🇸',
_("Flag of Spain"): '🇪🇸',
_("Flag of Italy"): '🇮🇹',
_("Flag of Japan"): '🇯🇵',
_("Flag of Russia"): '🇷🇺',
_("Black Flag"): '⚑',
_("Flag of the United Kingdom"): '🇬🇧',
_("Hammer And Pick"): '⚒',
_("Pick"): '⛏',
_("Anchor"): '⚓',
_("Crossed Swords"): '⚔',
_("Flower"): '⚘',
_("flower punctuation mark"): '⁕',
_("WHITE FLORETTE"): '❀',
_("Gear"): '⚙',
_("Staff Of Hermes"): '⚚',
_("Atomic Symbol"): '⚛',
_("Fleur-De-Lis"): '⚜',
_("Outlined White Star"): '⚝',
_("right-handed interlaced pentagram"): '⛥',
_("closed caption background speaker"): '⚟',
_("closed caption someone speaking"): '⚞',
_("Two Females"): '⚢',
_("Two Males"): '⚣',
_("Interlocked Female And Male"): '⚤',
_("Male And Female"): '⚥',
_("Male With Stroke Sign"): '⚦',
_("Male With Stroke And Male And Female Sign"): '⚧',
_("Medium White Circle"): '⚪',
_("Record"): '⚫',
_("Marriage"): '⚭',
_("Divorce"): '⚮',
_("vertical bar negated infinity"): '⧞',
_("Unmarried partnership"): '⚯',
_("double-ended multimap"): '⧟',
_("Coffin"): '⚰',
_("Funeral Urn"): '⚱',
_("neuter"): '⚲',
_("Soccer Ball"): '⚽',
_("Baseball"): '⚾',
_("Parental Lock"): '⚿',
_("Snowman"): '⛄',
_("Sun Behind Cloud"): '⛅',
_("Rain"): '⛆',
_("heavy snow"): '⛇',
_("Thunder storm"): '⛈',
_("Umbrella On Ground"): '⛱',
_("car crash"): '⛌',
_("Disabled Car"): '⛍',
_("Map Symbol For Lighthouse"): '⛯',
_("Mountain"): '⛰',
_("Fountain"): '⛲',
_("Golf Flag In Hole"): '⛳',
_("Ferry"): '⛴',
_("Sailboat"): '⛵',
_("intersection"): '⛶',
_("Inverted Pentagram"): '⛧',
_("Pentagram"): '⛤',
_("Skier"): '⛷',
_("Ice Skate"): '⛸',
_("Person With Ball"): '⛹',
_("Tent"): '⛺',
_("Japanese Bank"): '⛻',
_("Headstone"): '⛼',
_("Gas Pump"): '⛽',
_("Drive In"): '⛾',
_("White Flag With Horizontal Middle Black Stripe"): '⛿',
_("UPPER BLADE SCISSORS"): '✁',
_("BLACK SCISSORS"): '✂',
_("LOWER BLADE SCISSORS"): '✃',
_("WHITE SCISSORS"): '✄',
_("TAPE DRIVE"): '✇',
_("AIRPLANE"): '✈',
_("victorious hand"): '✌',
_("ENVELOPE"): '✉',
_("RAISED FIST"): '✊',
_("RAISED HAND"): '✋',
_("WRITING HAND"): '✍',
_("LOWER RIGHT PENCIL"): '✎',
_("PENCIL"): '✏',
_("UPPER RIGHT PENCIL"): '✐',
_("WHITE NIB"): '✑',
_("BLACK NIB"): '✒',
_("CHECK MARK"): '✓',
_("HEAVY CHECK MARK"): '✔',
_("MULTIPLICATION X"): '✕',
_("HEAVY MULTIPLICATION X"): '✖',
_("HEAVY BALLOT X"): '✘',
_("CROSS MARK"): '❌',
_("SHADOWED WHITE CIRCLE"): '❍',
_("NEGATIVE SQUARED CROSS MARK"): '❎',
_("LOWER RIGHT DROP-SHADOWED WHITE SQUARE"): '❏',
_("UPPER RIGHT DROP-SHADOWED WHITE SQUARE"): '❐',
_("LOWER RIGHT SHADOWED WHITE SQUARE"): '❑',
_("UPPER RIGHT SHADOWED WHITE SQUARE"): '❒',
_("BLACK QUESTION MARK ORNAMENT"): '❓',
_("WHITE QUESTION MARK ORNAMENT"): '❔',
_("WHITE EXCLAMATION MARK ORNAMENT"): '❕',
_("BLACK DIAMOND MINUS WHITE X"): '❖',
_("HEAVY EXCLAMATION MARK SYMBOL"): '❗',
_("Interrobang"): '⁉',
_("LIGHT VERTICAL BAR"): '❘',
_("MEDIUM VERTICAL BAR"): '❙',
_("HEAVY VERTICAL BAR"): '❚',
_("CURLY LOOP"): '➰',
_("DOUBLE CURLY LOOP"): '➿',
_("Dash"): '〰',
_("OUTLINED GREEK CROSS"): '✙',
_("HEAVY GREEK CROSS"): '✚',
_("OPEN CENTRE CROSS"): '✛',
_("HEAVY OPEN CENTRE CROSS"): '✜',
_("LATIN CROSS"): '✝',
_("SHADOWED WHITE LATIN CROSS"): '✞',
_("OUTLINED LATIN CROSS"): '✟',
_("MALTESE CROSS"): '✠',
_("STAR OF DAVID"): '✡',
_("FOUR TEARDROP-SPOKED ASTERISK"): '✢',
_("FOUR BALLOON-SPOKED ASTERISK"): '✣',
_("HEAVY FOUR BALLOON-SPOKED ASTERISK"): '✤',
_("FOUR CLUB-SPOKED ASTERISK"): '✥',
_("BLACK FOUR POINTED STAR"): '✦',
_("WHITE FOUR POINTED STAR"): '✧',
_("SPARKLES"): '✨',
_("CIRCLED WHITE STAR"): '✪',
_("OPEN CENTRE BLACK STAR"): '✫',
_("BLACK CENTRE WHITE STAR"): '✬',
_("OUTLINED BLACK STAR"): '✭',
_("HEAVY OUTLINED BLACK STAR"): '✮',
_("PINWHEEL STAR"): '✯',
_("SHADOWED WHITE STAR"): '✰',
_("HEAVY ASTERISK"): '✱',
_("OPEN CENTRE ASTERISK"): '✲',
_("EIGHT SPOKED ASTERISK"): '✳',
_("EIGHT POINTED BLACK STAR"): '✴',
_("EIGHT POINTED PINWHEEL STAR"): '✵',
_("SIX POINTED BLACK STAR"): '✶',
_("EIGHT POINTED RECTILINEAR BLACK STAR"): '✷',
_("HEAVY EIGHT POINTED RECTILINEAR BLACK STAR"): '✸',
_("TWELVE POINTED BLACK STAR"): '✹',
_("SIXTEEN POINTED ASTERISK"): '✺',
_("TEARDROP-SPOKED ASTERISK"): '✻',
_("OPEN CENTRE TEARDROP-SPOKED ASTERISK"): '✼',
_("HEAVY TEARDROP-SPOKED ASTERISK"): '✽',
_("SIX PETALLED BLACK AND WHITE FLORETTE"): '✾',
_("BLACK FLORETTE"): '✿',
_("EIGHT PETALLED OUTLINED BLACK FLORETTE"): '❁',
_("CIRCLED OPEN CENTRE EIGHT POINTED STAR"): '❂',
_("HEAVY TEARDROP-SPOKED PINWHEEL ASTERISK"): '❃',
_("SNOWFLAKE"): '❄',
_("TIGHT TRIFOLIATE SNOWFLAKE"): '❅',
_("HEAVY CHEVRON SNOWFLAKE"): '❆',
_("SPARKLE"): '❇',
_("HEAVY SPARKLE"): '❈',
_("BALLOON-SPOKED ASTERISK"): '❉',
_("EIGHT TEARDROP-SPOKED PROPELLER ASTERISK"): '❊',
_("HEAVY EIGHT TEARDROP-SPOKED PROPELLER ASTERISK"): '❋',
_("HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT"): '❛',
_("HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT"): '❜',
_("HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT"): '❝',
_("HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT"): '❞',
_("HEAVY LOW SINGLE COMMA QUOTATION MARK ORNAMENT"): '❟',
_("HEAVY LOW DOUBLE COMMA QUOTATION MARK ORNAMENT"): '❠',
_("CURVED STEM PARAGRAPH SIGN ORNAMENT"): '❡',
_("HEAVY EXCLAMATION MARK ORNAMENT"): '❢',
_("HEAVY HEART EXCLAMATION MARK ORNAMENT"): '❣',
_("HEAVY BLACK HEART"): '❤',
_("ROTATED HEAVY BLACK HEART BULLET"): '❥',
_("FLORAL HEART"): '❦',
_("MEDIUM LEFT PARENTHESIS ORNAMENT"): '❨',
_("MEDIUM RIGHT PARENTHESIS ORNAMENT"): '❩',
_("MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT"): '❪',
_("MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT"): '❫',
_("MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT"): '❬',
_("MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT"): '❭',
_("HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT"): '❮',
_("HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT"): '❯',
_("HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT"): '❰',
_("HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT"): '❱',
_("LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT"): '❲',
_("LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT"): '❳',
_("MEDIUM LEFT CURLY BRACKET ORNAMENT"): '❴',
_("MEDIUM RIGHT CURLY BRACKET ORNAMENT"): '❵',
_("DINGBAT NEGATIVE CIRCLED DIGIT ONE"): '❶',
_("DINGBAT NEGATIVE CIRCLED DIGIT TWO"): '❷',
_("DINGBAT NEGATIVE CIRCLED DIGIT THREE"): '❸',
_("DINGBAT NEGATIVE CIRCLED DIGIT FOUR"): '❹',
_("DINGBAT NEGATIVE CIRCLED DIGIT FIVE"): '❺',
_("DINGBAT NEGATIVE CIRCLED DIGIT SIX"): '❻',
_("DINGBAT NEGATIVE CIRCLED DIGIT SEVEN"): '❼',
_("DINGBAT NEGATIVE CIRCLED DIGIT EIGHT"): '❽',
_("DINGBAT NEGATIVE CIRCLED DIGIT NINE"): '❾',
_("DINGBAT NEGATIVE CIRCLED NUMBER TEN"): '❿',
_("DINGBAT CIRCLED SANS-SERIF DIGIT ONE"): '➀',
_("DINGBAT CIRCLED SANS-SERIF DIGIT TWO"): '➁',
_("DINGBAT CIRCLED SANS-SERIF DIGIT THREE"): '➂',
_("DINGBAT CIRCLED SANS-SERIF DIGIT FOUR"): '➃',
_("DINGBAT CIRCLED SANS-SERIF DIGIT FIVE"): '➄',
_("DINGBAT CIRCLED SANS-SERIF DIGIT SIX"): '➅',
_("DINGBAT CIRCLED SANS-SERIF DIGIT SEVEN"): '➆',
_("DINGBAT CIRCLED SANS-SERIF DIGIT EIGHT"): '➇',
_("DINGBAT CIRCLED SANS-SERIF DIGIT NINE"): '➈',
_("DINGBAT CIRCLED SANS-SERIF NUMBER TEN"): '➉',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT ONE"): '➊',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT TWO"): '➋',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT THREE"): '➌',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT FOUR"): '➍',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT FIVE"): '➎',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT SIX"): '➏',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT SEVEN"): '➐',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT EIGHT"): '➑',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT NINE"): '➒',
_("DINGBAT NEGATIVE CIRCLED SANS-SERIF NUMBER TEN"): '➓',
_("HEAVY SOUTH EAST ARROW"): '➘',
_("HEAVY RIGHTWARDS ARROW"): '➙',
_("HEAVY NORTH EAST ARROW"): '➚',
_("DRAFTING POINT RIGHTWARDS ARROW"): '➛',
_("HEAVY ROUND-TIPPED RIGHTWARDS ARROW"): '➜',
_("TRIANGLE-HEADED RIGHTWARDS ARROW"): '➝',
_("HEAVY TRIANGLE-HEADED RIGHTWARDS ARROW"): '➞',
_("DASHED TRIANGLE-HEADED RIGHTWARDS ARROW"): '➟',
_("HEAVY DASHED TRIANGLE-HEADED RIGHTWARDS ARROW"): '➠',
_("BLACK RIGHTWARDS ARROW"): '➡',
_("THREE-D TOP-LIGHTED RIGHTWARDS ARROW HEAD"): '➢',
_("THREE-D BOTTOM-LIGHTED RIGHTWARDS ARROW HEAD"): '➣',
_("BLACK RIGHTWARDS ARROWHEAD"): '➤',
_("HEAVY BLACK CURVED DOWNWARDS AND RIGHTWARDS ARROW"): '➥',
_("HEAVY BLACK CURVED UPWARDS AND RIGHTWARDS ARROW"): '➦',
_("SQUAT BLACK RIGHTWARDS ARROW"): '➧',
_("HEAVY CONCAVE-POINTED BLACK RIGHTWARDS ARROW"): '➨',
_("RIGHT-SHADED WHITE RIGHTWARDS ARROW"): '➩',
_("LEFT-SHADED WHITE RIGHTWARDS ARROW"): '➪',
_("BACK-TILTED SHADOWED WHITE RIGHTWARDS ARROW"): '➫',
_("FRONT-TILTED SHADOWED WHITE RIGHTWARDS ARROW"): '➬',
_("HEAVY LOWER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW"): '➭',
_("HEAVY UPPER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW"): '➮',
_("NOTCHED LOWER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW"): '➯',
_("NOTCHED UPPER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW"): '➱',
_("CIRCLED HEAVY WHITE RIGHTWARDS ARROW"): '➲',
_("WHITE-FEATHERED RIGHTWARDS ARROW"): '➳',
_("BLACK-FEATHERED SOUTH EAST ARROW"): '➴',
_("BLACK-FEATHERED RIGHTWARDS ARROW"): '➵',
_("BLACK-FEATHERED NORTH EAST ARROW"): '➶',
_("HEAVY BLACK-FEATHERED SOUTH EAST ARROW"): '➷',
_("HEAVY BLACK-FEATHERED RIGHTWARDS ARROW"): '➸',
_("HEAVY BLACK-FEATHERED NORTH EAST ARROW"): '➹',
_("TEARDROP-BARBED RIGHTWARDS ARROW"): '➺',
_("HEAVY TEARDROP-SHANKED RIGHTWARDS ARROW"): '➻',
_("WEDGE-TAILED RIGHTWARDS ARROW"): '➼',
_("HEAVY WEDGE-TAILED RIGHTWARDS ARROW"): '➽',
_("OPEN-OUTLINED RIGHTWARDS ARROW"): '➾',
_("HEAVY MINUS SIGN"): '➖',
_("HEAVY DIVISION SIGN"): '➗',
_("playing card back"): '🂠',
_("ace of spades"): '🂡',
_("TWO OF SPADES"): '🂢',
_("Three Of SPADES"): '🂣',
_("FOUR OF SPADES"): '🂤',
_("FIVE OF SPADES"): '🂥',
_("SIX OF SPADES"): '🂦',
_("SEVEN OF SPADES"): '🂧',
_("EIGHT OF SPADES"): '🂨',
_("NINE OF SPADES"): '🂩',
_("TEN OF SPADES"): '🂪',
_("JACK OF SPADES"): '🂫',
_("KNIGHT OF SPADES"): '🂬',
_("QUEEN OF SPADES"): '🂭',
_("KING OF SPADES"): '🂮',
_("ACE OF HEARTS"): '🂱',
_("TWO OF HEARTS"): '🂲',
_("THREE OF HEARTS"): '🂳',
_("FOUR OF HEARTS"): '🂴',
_("FIVE OF HEARTS"): '🂵',
_("SIX OF HEARTS"): '🂶',
_("SEVEN OF HEARTS"): '🂷',
_("EIGHT OF HEARTS"): '🂸',
_("NINE OF HEARTS"): '🂹',
_("TEN OF HEARTS"): '🂺',
_("JACK OF HEARTS"): '🂻',
_("KNIGHT OF HEARTS"): '🂼',
_("QUEEN OF HEARTS"): '🂽',
_("KING OF HEARTS"): '🂾',
_("ACE OF DIAMONDS"): '🃁',
_("TWO OF DIAMONDS"): '🃂',
_("THREE OF DIAMONDS"): '🃃',
_("FOUR OF DIAMONDS"): '🃄',
_("FIVE OF DIAMONDS"): '🃅',
_("SIX OF DIAMONDS"): '🃆',
_("SEVEN OF DIAMONDS"): '🃇',
_("EIGHT OF DIAMONDS"): '🃈',
_("NINE OF DIAMONDS"): '🃉',
_("TEN OF DIAMONDS"): '🃊',
_("JACK OF DIAMONDS"): '🃋',
_("KNIGHT OF DIAMONDS"): '🃌',
_("QUEEN OF DIAMONDS"): '🃍',
_("KING OF DIAMONDS"): '🃎',
_("BLACK JOKER"): '🃏',
_("WHITE JOKER"): '🃟',
_("ACE OF CLUBS"): '🃑',
_("TWO OF CLUBS"): '🃒',
_("THREE OF CLUBS"): '🃓',
_("FOUR OF CLUBS"): '🃔',
_("FIVE OF CLUBS"): '🃕',
_("SIX OF CLUBS"): '🃖',
_("SEVEN OF CLUBS"): '🃗',
_("EIGHT OF CLUBS"): '🃘',
_("NINE OF CLUBS"): '🃙',
_("TEN OF CLUBS"): '🃚',
_("JACK OF CLUBS"): '🃛',
_("KNIGHT OF CLUBS"): '🃜',
_("QUEEN OF CLUBS"): '🃝',
_("KING OF CLUBS"): '🃞',
_("DIE FACE-1"): '⚀',
_("DIE FACE-2"): '⚁',
_("DIE FACE-3"): '⚂',
_("DIE FACE-4"): '⚃',
_("DIE FACE-5"): '⚄',
_("DIE FACE-6"): '⚅',
_("SPADE SUIT"): '♠',
_("CLUB SUIT"): '♣',
_("HEART SUIT"): '♥',
_("DIAMOND SUIT"): '♦',
_("EURO-CURRENCY"): '₠',
_("CENTS"): '₡',
_("CRUZEIRO SIGN"): '₢',
_("FRENCH FRANC"): '₣',
_("MILL SIGN"): '₥',
_("NAIRA SIGN"): '₦',
_("PESETA"): '₧',
_("RUPEE"): '₨',
_("WON SIGN"): '₩',
_("NEW SHEQEL SIGN"): '₪',
_("DONG SIGN"): '₫',
_("KIP SIGN"): '₭',
_("TUGRIK SIGN"): '₮',
_("DRACHMA SIGN"): '₯',
_("GERMAN PENNIES"): '₰',
_("PESO"): '₱',
_("GUARANI SIGN"): '₲',
_("AUSTRAL SIGN"): '₳',
_("HRYVNIA SIGN"): '₴',
_("CEDI SIGN"): '₵',
_("LIVRE TOURNOIS SIGN"): '₶',
_("SPESMILO SIGN"): '₷',
_("TENGE SIGN"): '₸',
_("INDIAN RUPEE"): '₹',
_("DOMINO TILE HORIZONTAL-00-00"): '🀱',
_("DOMINO TILE HORIZONTAL-00-01"): '🀲',
_("DOMINO TILE HORIZONTAL-00-02"): '🀳',
_("DOMINO TILE HORIZONTAL-00-03"): '🀴',
_("DOMINO TILE HORIZONTAL-00-04"): '🀵',
_("DOMINO TILE HORIZONTAL-00-05"): '🀶',
_("DOMINO TILE HORIZONTAL-00-06"): '🀷',
_("DOMINO TILE VERTICAL-00-00"): '🁣',
_("DOMINO TILE VERTICAL-00-01"): '🁤',
_("DOMINO TILE VERTICAL-00-02"): '🁥',
_("DOMINO TILE VERTICAL-00-03"): '🁦',
_("DOMINO TILE VERTICAL-00-04"): '🁧',
_("DOMINO TILE VERTICAL-00-05"): '🁨',
_("DOMINO TILE VERTICAL-00-06"): '🁩',
_("DOMINO TILE HORIZONTAL-01-00"): '🀸',
_("DOMINO TILE HORIZONTAL-01-01"): '🀹',
_("DOMINO TILE HORIZONTAL-01-02"): '🀺',
_("DOMINO TILE HORIZONTAL-01-03"): '🀻',
_("DOMINO TILE HORIZONTAL-01-04"): '🀼',
_("DOMINO TILE HORIZONTAL-01-05"): '🀽',
_("DOMINO TILE HORIZONTAL-01-06"): '🀾',
_("DOMINO TILE VERTICAL-01-00"): '🁪',
_("DOMINO TILE VERTICAL-01-01"): '🁫',
_("DOMINO TILE VERTICAL-01-02"): '🁬',
_("DOMINO TILE VERTICAL-01-03"): '🁭',
_("DOMINO TILE VERTICAL-01-04"): '🁮',
_("DOMINO TILE VERTICAL-01-05"): '🁯',
_("DOMINO TILE VERTICAL-01-06"): '🁰',
_("DOMINO TILE HORIZONTAL-02-00"): '🀿',
_("DOMINO TILE HORIZONTAL-02-01"): '🁀',
_("DOMINO TILE HORIZONTAL-02-02"): '🁁',
_("DOMINO TILE HORIZONTAL-02-03"): '🁂',
_("DOMINO TILE HORIZONTAL-02-04"): '🁃',
_("DOMINO TILE HORIZONTAL-02-05"): '🁄',
_("DOMINO TILE HORIZONTAL-02-06"): '🁅',
_("DOMINO TILE VERTICAL-02-00"): '🁱',
_("DOMINO TILE VERTICAL-02-01"): '🁲',
_("DOMINO TILE VERTICAL-02-02"): '🁳',
_("DOMINO TILE VERTICAL-02-03"): '🁴',
_("DOMINO TILE VERTICAL-02-04"): '🁵',
_("DOMINO TILE VERTICAL-02-05"): '🁶',
_("DOMINO TILE VERTICAL-02-06"): '🁷',
_("DOMINO TILE HORIZONTAL-03-00"): '🁆',
_("DOMINO TILE HORIZONTAL-03-01"): '🁇',
_("DOMINO TILE HORIZONTAL-03-02"): '🁈',
_("DOMINO TILE HORIZONTAL-03-03"): '🁉',
_("DOMINO TILE HORIZONTAL-03-04"): '🁊',
_("DOMINO TILE HORIZONTAL-03-05"): '🁋',
_("DOMINO TILE HORIZONTAL-03-06"): '🁌',
_("DOMINO TILE VERTICAL-03-00"): '🁸',
_("DOMINO TILE VERTICAL-03-01"): '🁹',
_("DOMINO TILE VERTICAL-03-02"): '🁺',
_("DOMINO TILE VERTICAL-03-03"): '🁻',
_("DOMINO TILE VERTICAL-03-04"): '🁼',
_("DOMINO TILE VERTICAL-03-05"): '🁽',
_("DOMINO TILE VERTICAL-03-06"): '🁾',
_("DOMINO TILE HORIZONTAL-04-00"): '🁍',
_("DOMINO TILE HORIZONTAL-04-01"): '🁎',
_("DOMINO TILE HORIZONTAL-04-02"): '🁏',
_("DOMINO TILE HORIZONTAL-04-03"): '🁐',
_("DOMINO TILE HORIZONTAL-04-04"): '🁑',
_("DOMINO TILE HORIZONTAL-04-05"): '🁒',
_("DOMINO TILE HORIZONTAL-04-06"): '🁓',
_("DOMINO TILE VERTICAL-04-00"): '🁿',
_("DOMINO TILE VERTICAL-04-01"): '🂀',
_("DOMINO TILE VERTICAL-04-02"): '🂁',
_("DOMINO TILE VERTICAL-04-03"): '🂂',
_("DOMINO TILE VERTICAL-04-04"): '🂃',
_("DOMINO TILE VERTICAL-04-05"): '🂄',
_("DOMINO TILE VERTICAL-04-06"): '🂅',
_("DOMINO TILE HORIZONTAL-05-00"): '🁔',
_("DOMINO TILE HORIZONTAL-05-01"): '🁕',
_("DOMINO TILE HORIZONTAL-05-02"): '🁖',
_("DOMINO TILE HORIZONTAL-05-03"): '🁗',
_("DOMINO TILE HORIZONTAL-05-04"): '🁘',
_("DOMINO TILE HORIZONTAL-05-05"): '🁙',
_("DOMINO TILE HORIZONTAL-05-06"): '🁚',
_("DOMINO TILE VERTICAL-05-00"): '🂆',
_("DOMINO TILE VERTICAL-05-01"): '🂇',
_("DOMINO TILE VERTICAL-05-02"): '🂈',
_("DOMINO TILE VERTICAL-05-03"): '🂉',
_("DOMINO TILE VERTICAL-05-04"): '🂊',
_("DOMINO TILE VERTICAL-05-05"): '🂋',
_("DOMINO TILE VERTICAL-05-06"): '🂌',
_("DOMINO TILE HORIZONTAL-06-00"): '🁛',
_("DOMINO TILE HORIZONTAL-06-01"): '🁜',
_("DOMINO TILE HORIZONTAL-06-02"): '🁝',
_("DOMINO TILE HORIZONTAL-06-03"): '🁞',
_("DOMINO TILE HORIZONTAL-06-04"): '🁟',
_("DOMINO TILE HORIZONTAL-06-05"): '🁠',
_("DOMINO TILE HORIZONTAL-06-06"): '🁡',
_("DOMINO TILE VERTICAL-06-00"): '🂍',
_("DOMINO TILE VERTICAL-06-01"): '🂎',
_("DOMINO TILE VERTICAL-06-02"): '🂏',
_("DOMINO TILE VERTICAL-06-03"): '🂐',
_("DOMINO TILE VERTICAL-06-04"): '🂑',
_("DOMINO TILE VERTICAL-06-05"): '🂒',
_("DOMINO TILE VERTICAL-06-06"): '🂓',
_("DOMINO TILE VERTICAL BACK"): '🁢',
_("COMPLEMENT"): '∁',
_("PARTIAL DIFFERENTIAL"): '∂',
_("THERE EXISTS"): '∃',
_("THERE DOES NOT EXIST"): '∄',
_("EMPTY SET"): '∅',
_("INCREMENT"): '∆',
_("NABLA"): '∇',
_("END OF PROOF"): '∎',
_("RIGHT ANGLE"): '∟',
_("ANGLE"): '∠',
_("MEASURED ANGLE"): '∡',
_("SPHERICAL ANGLE"): '∢',
_("THEREFORE"): '∴',
_("BECAUSE"): '∵',
_("SINE WAVE"): '∿',
_("DOWN TACK"): '⊤',
_("UP TACK"): '⊥',
_("RIGHT ANGLE WITH ARC"): '⊾',
_("RIGHT TRIANGLE"): '⊿',
_("ELEMENT OF"): '∈',
_("NOT AN ELEMENT OF"): '∉',
_("SMALL ELEMENT OF"): '∊',
_("CONTAINS AS MEMBER"): '∋',
_("DOES NOT CONTAIN AS MEMBER"): '∌',
_("SMALL CONTAINS AS MEMBER"): '∍',
_("N-ARY PRODUCT"): '∏',
_("N-ARY COPRODUCT"): '∐',
_("N-ARY SUMMATION"): '∑',
_("N-ARY LOGICAL AND"): '⋀',
_("N-ARY LOGICAL OR"): '⋁',
_("N-ARY INTERSECTION"): '⋂',
_("N-ARY UNION"): '⋃',
_("MINUS SIGN"): '−',
_("MINUS-OR-PLUS SIGN"): '∓',
_("DOT PLUS"): '∔',
_("DIVISION SLASH"): '∕',
_("SET MINUS"): '∖',
_("ASTERISK OPERATOR"): '∗',
_("RING OPERATOR"): '∘',
_("BULLET OPERATOR"): '∙',
_("SQUARE ROOT"): '√',
_("CUBE ROOT"): '∛',
_("FOURTH ROOT"): '∜',
_("PROPORTIONAL TO"): '∝',
_("DOT MINUS"): '∸',
_("GEOMETRIC PROPORTION"): '∺',
_("WREATH PRODUCT"): '≀',
_("MULTISET"): '⊌',
_("MULTISET MULTIPLICATION"): '⊍',
_("MULTISET UNION"): '⊎',
_("SQUARE CAP"): '⊓',
_("SQUARE CUP"): '⊔',
_("CIRCLED PLUS"): '⊕',
_("CIRCLED MINUS"): '⊖',
_("CIRCLED TIMES"): '⊗',
_("CIRCLED DIVISION SLASH"): '⊘',
_("CIRCLED DOT OPERATOR"): '⊙',
_("CIRCLED RING OPERATOR"): '⊚',
_("CIRCLED ASTERISK OPERATOR"): '⊛',
_("CIRCLED EQUALS"): '⊜',
_("CIRCLED DASH"): '⊝',
_("SQUARED PLUS"): '⊞',
_("SQUARED MINUS"): '⊟',
_("SQUARED DOT OPERATOR"): '⊡',
_("RIGHT TACK"): '⊢',
_("LEFT TACK"): '⊣',
_("INTERCALATE"): '⊺',
_("XOR"): '⊻',
_("NAND"): '⊼',
_("NOR"): '⊽',
_("DIAMOND OPERATOR"): '⋄',
_("DOT OPERATOR"): '⋅',
_("DIVISION TIMES"): '⋇',
_("LEFT NORMAL FACTOR SEMIDIRECT PRODUCT"): '⋉',
_("RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT"): '⋊',
_("LEFT SEMIDIRECT PRODUCT"): '⋋',
_("RIGHT SEMIDIRECT PRODUCT"): '⋌',
_("DOUBLE INTERSECTION"): '⋒',
_("DOUBLE UNION"): '⋓',
_("DIVIDES"): '∣',
_("DOES NOT DIVIDE"): '∤',
_("PARALLEL TO"): '∥',
_("NOT PARALLEL TO"): '∦',
_("RATIO"): '∶',
_("PROPORTION"): '∷',
_("EXCESS"): '∹',
_("HOMOTHETIC"): '∻',
_("TILDE OPERATOR"): '∼',
_("REVERSED TILDE"): '∽',
_("INVERTED LAZY S"): '∾',
_("NOT TILDE"): '≁',
_("MINUS TILDE"): '≂',
_("ASYMPTOTICALLY EQUAL TO"): '≃',
_("NOT ASYMPTOTICALLY EQUAL TO"): '≄',
_("APPROXIMATELY EQUAL TO"): '≅',
_("APPROXIMATELY BUT NOT ACTUALLY EQUAL TO"): '≆',
_("NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO"): '≇',
_("ALMOST EQUAL TO"): '≈',
_("NOT ALMOST EQUAL TO"): '≉',
_("ALMOST EQUAL OR EQUAL TO"): '≊',
_("TRIPLE TILDE"): '≋',
_("ALL EQUAL TO"): '≌',
_("EQUIVALENT TO"): '≍',
_("GEOMETRICALLY EQUIVALENT TO"): '≎',
_("DIFFERENCE BETWEEN"): '≏',
_("APPROACHES THE LIMIT"): '≐',
_("GEOMETRICALLY EQUAL TO"): '≑',
_("APPROXIMATELY EQUAL TO OR THE IMAGE OF"): '≒',
_("IMAGE OF OR APPROXIMATELY EQUAL TO"): '≓',
_("COLON EQUALS"): '≔',
_("EQUALS COLON"): '≕',
_("RING IN EQUAL TO"): '≖',
_("RING EQUAL TO"): '≗',
_("CORRESPONDS TO"): '≘',
_("ESTIMATES"): '≙',
_("EQUIANGULAR TO"): '≚',
_("STAR EQUALS"): '≛',
_("DELTA EQUAL TO"): '≜',
_("EQUAL TO BY DEFINITION"): '≝',
_("MEASURED BY"): '≞',
_("QUESTIONED EQUAL TO"): '≟',
_("NOT EQUAL TO"): '≠',
_("IDENTICAL TO"): '≡',
_("NOT IDENTICAL TO"): '≢',
_("STRICTLY EQUIVALENT TO"): '≣',
_("LESS-THAN OR EQUAL TO"): '≤',
_("GREATER-THAN OR EQUAL TO"): '≥',
_("LESS-THAN OVER EQUAL TO"): '≦',
_("GREATER-THAN OVER EQUAL TO"): '≧',
_("LESS-THAN BUT NOT EQUAL TO"): '≨',
_("GREATER-THAN BUT NOT EQUAL TO"): '≩',
_("MUCH LESS-THAN"): '≪',
_("MUCH GREATER-THAN"): '≫',
_("BETWEEN"): '≬',
_("NOT EQUIVALENT TO"): '≭',
_("NOT LESS-THAN"): '≮',
_("NOT GREATER-THAN"): '≯',
_("NEITHER LESS-THAN NOR EQUAL TO"): '≰',
_("NEITHER GREATER-THAN NOR EQUAL TO"): '≱',
_("LESS-THAN OR EQUIVALENT TO"): '≲',
_("GREATER-THAN OR EQUIVALENT TO"): '≳',
_("NEITHER LESS-THAN NOR EQUIVALENT TO"): '≴',
_("NEITHER GREATER-THAN NOR EQUIVALENT TO"): '≵',
_("LESS-THAN OR GREATER-THAN"): '≶',
_("GREATER-THAN OR LESS-THAN"): '≷',
_("NEITHER LESS-THAN NOR GREATER-THAN"): '≸',
_("NEITHER GREATER-THAN NOR LESS-THAN"): '≹',
_("PRECEDES"): '≺',
_("SUCCEEDS"): '≻',
_("PRECEDES OR EQUAL TO"): '≼',
_("SUCCEEDS OR EQUAL TO"): '≽',
_("PRECEDES OR EQUIVALENT TO"): '≾',
_("SUCCEEDS OR EQUIVALENT TO"): '≿',
_("DOES NOT PRECEDE"): '⊀',
_("DOES NOT SUCCEED"): '⊁',
_("SUBSET OF"): '⊂',
_("SUPERSET OF"): '⊃',
_("NOT A SUBSET OF"): '⊄',
_("NOT A SUPERSET OF"): '⊅',
_("SUBSET OF OR EQUAL TO"): '⊆',
_("SUPERSET OF OR EQUAL TO"): '⊇',
_("NEITHER A SUBSET OF NOR EQUAL TO"): '⊈',
_("NEITHER A SUPERSET OF NOR EQUAL TO"): '⊉',
_("SUBSET OF WITH NOT EQUAL TO"): '⊊',
_("SUPERSET OF WITH NOT EQUAL TO"): '⊋',
_("SQUARE IMAGE OF"): '⊏',
_("SQUARE ORIGINAL OF"): '⊐',
_("SQUARE IMAGE OF OR EQUAL TO"): '⊑',
_("SQUARE ORIGINAL OF OR EQUAL TO"): '⊒',
_("ASSERTION"): '⊦',
_("MODELS"): '⊧',
_("TRUE"): '⊨',
_("FORCES"): '⊩',
_("TRIPLE VERTICAL BAR RIGHT TURNSTILE"): '⊪',
_("DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE"): '⊫',
_("DOES NOT PROVE"): '⊬',
_("NOT TRUE"): '⊭',
_("DOES NOT FORCE"): '⊮',
_("NEGATED DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE"): '⊯',
_("PRECEDES UNDER RELATION"): '⊰',
_("SUCCEEDS UNDER RELATION"): '⊱',
_("NORMAL SUBGROUP OF"): '⊲',
_("CONTAINS AS NORMAL SUBGROUP"): '⊳',
_("NORMAL SUBGROUP OF OR EQUAL TO"): '⊴',
_("CONTAINS AS NORMAL SUBGROUP OR EQUAL TO"): '⊵',
_("ORIGINAL OF"): '⊶',
_("IMAGE OF"): '⊷',
_("MULTIMAP"): '⊸',
_("HERMITIAN CONJUGATE MATRIX"): '⊹',
_("BOWTIE"): '⋈',
_("REVERSED TILDE EQUALS"): '⋍',
_("DOUBLE SUBSET"): '⋐',
_("DOUBLE SUPERSET"): '⋑',
_("PITCHFORK"): '⋔',
_("EQUAL AND PARALLEL TO"): '⋕',
_("LESS-THAN WITH DOT"): '⋖',
_("GREATER-THAN WITH DOT"): '⋗',
_("VERY MUCH LESS-THAN"): '⋘',
_("VERY MUCH GREATER-THAN"): '⋙',
_("LESS-THAN EQUAL TO OR GREATER-THAN"): '⋚',
_("GREATER-THAN EQUAL TO OR LESS-THAN"): '⋛',
_("EQUAL TO OR LESS-THAN"): '⋜',
_("EQUAL TO OR GREATER-THAN"): '⋝',
_("EQUAL TO OR PRECEDES"): '⋞',
_("EQUAL TO OR SUCCEEDS"): '⋟',
_("DOES NOT PRECEDE OR EQUAL"): '⋠',
_("DOES NOT SUCCEED OR EQUAL"): '⋡',
_("NOT SQUARE IMAGE OF OR EQUAL TO"): '⋢',
_("NOT SQUARE ORIGINAL OF OR EQUAL TO"): '⋣',
_("SQUARE IMAGE OF OR NOT EQUAL TO"): '⋤',
_("SQUARE ORIGINAL OF OR NOT EQUAL TO"): '⋥',
_("LESS-THAN BUT NOT EQUIVALENT TO"): '⋦',
_("GREATER-THAN BUT NOT EQUIVALENT TO"): '⋧',
_("PRECEDES BUT NOT EQUIVALENT TO"): '⋨',
_("SUCCEEDS BUT NOT EQUIVALENT TO"): '⋩',
_("NOT NORMAL SUBGROUP OF"): '⋪',
_("DOES NOT CONTAIN AS NORMAL SUBGROUP"): '⋫',
_("NOT NORMAL SUBGROUP OF OR EQUAL TO"): '⋬',
_("DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL"): '⋭',
_("VERTICAL ELLIPSIS"): '⋮',
_("MIDLINE HORIZONTAL ELLIPSIS"): '⋯',
_("UP RIGHT DIAGONAL ELLIPSIS"): '⋰',
_("DOWN RIGHT DIAGONAL ELLIPSIS"): '⋱',
_("ELEMENT OF WITH LONG HORIZONTAL STROKE"): '⋲',
_("ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE"): '⋳',
_("SMALL ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE"): '⋴',
_("ELEMENT OF WITH DOT ABOVE"): '⋵',
_("ELEMENT OF WITH OVERBAR"): '⋶',
_("SMALL ELEMENT OF WITH OVERBAR"): '⋷',
_("ELEMENT OF WITH UNDERBAR"): '⋸',
_("ELEMENT OF WITH TWO HORIZONTAL STROKES"): '⋹',
_("CONTAINS WITH LONG HORIZONTAL STROKE"): '⋺',
_("CONTAINS WITH VERTICAL BAR AT END F HORIZONTAL STROKE"): '⋻',
_("SMALL CONTAINS WITH VERTICAL BAR T END OF HORIZONTAL STROKE"): '⋼',
_("CONTAINS WITH OVERBAR"): '⋽',
_("SMALL CONTAINS WITH OVERBAR"): '⋾',
_("Z NOTATION BAG MEMBERSHIP"): '⋿',
_("LOGICAL AND"): '∧',
_("LOGICAL OR"): '∨',
_("INTERSECTION"): '∩',
_("UNION"): '∪',
_("INTEGRAL"): '∫',
_("DOUBLE INTEGRAL"): '∬',
_("TRIPLE INTEGRAL"): '∭',
_("CONTOUR INTEGRAL"): '∮',
_("SURFACE INTEGRAL"): '∯',
_("VOLUME INTEGRAL"): '∰',
_("CLOCKWISE INTEGRAL"): '∱',
_("CLOCKWISE CONTOUR INTEGRAL"): '∲',
_("ANTICLOCKWISE CONTOUR INTEGRAL"): '∳',
_("CURLY LOGICAL OR"): '⋎',
_("CURLY LOGICAL AND"): '⋏',
_("DIAMETER SIGN"): '⌀',
_("ELECTRIC ARROW"): '⌁',
_("HOUSE"): '⌂',
_("UP ARROWHEAD"): '⌃',
_("DOWN ARROWHEAD"): '⌄',
_("PROJECTIVE"): '⌅',
_("PERSPECTIVE"): '⌆',
_("WAVY LINE"): '⌇',
_("REVERSED NOT SIGN"): '⌐',
_("SQUARE LOZENGE"): '⌑',
_("ARC"): '⌒',
_("SEGMENT"): '⌓',
_("SECTOR"): '⌔',
_("TELEPHONE RECORDER"): '⌕',
_("POSITION INDICATOR"): '⌖',
_("VIEWDATA SQUARE"): '⌗',
_("PLACE OF INTEREST SIGN"): '⌘',
_("TURNED NOT SIGN"): '⌙',
_("RIGHT ANGLE WITH DOWNWARDS ZIGZAG RROW"): '⍼',
_("SQUARE FOOT"): '⏍',
_("WHITE TRAPEZIUM"): '⏢',
_("STRAIGHTNESS"): '⏤',
_("FLATNESS"): '⏥',
_("AC CURRENT"): '⏦',
_("ELECTRICAL INTERSECTION"): '⏧',
_("DECIMAL EXPONENT SYMBOL"): '⏨',
_("LEFT CEILING"): '⌈',
_("RIGHT CEILING"): '⌉',
_("LEFT FLOOR"): '⌊',
_("RIGHT FLOOR"): '⌋',
_("BOTTOM RIGHT CROP"): '⌌',
_("BOTTOM LEFT CROP"): '⌍',
_("TOP RIGHT CROP"): '⌎',
_("TOP LEFT CROP"): '⌏',
_("BLACK RIGHT-POINTING DOUBLE TRIANGLE"): '⏩',
_("BLACK LEFT-POINTING DOUBLE TRIANGLE"): '⏪',
_("BLACK UP-POINTING DOUBLE TRIANGLE"): '⏫',
_("BLACK DOWN-POINTING DOUBLE TRIANGLE"): '⏬',
_("BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR"): '⏭',
_("BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR"): '⏮',
_("BLACK RIGHT-POINTING TRIANGLE WITH OUBLE VERTICAL BAR"): '⏯',
_("ALARM CLOCK"): '⏰',
_("STOPWATCH"): '⏱',
_("TIMER CLOCK"): '⏲',
_("HOUR GLASS WITH FLOWING SAND"): '⏳',
_("TOP RIGHT CORNER"): '⌝',
_("BOTTOM LEFT CORNER"): '⌞',
_("BOTTOM RIGHT CORNER"): '⌟',
_("TOP HALF INTEGRAL"): '⌠',
_("BOTTOM HALF INTEGRAL"): '⌡',
_("FROWN"): '⌢',
_("SMILE"): '⌣',
_("UP ARROWHEAD BETWEEN TWO HORIZONTAL BARS"): '⌤',
_("OPTION KEY"): '⌥',
_("ERASE TO THE RIGHT"): '⌦',
_("X IN A RECTANGLE BOX"): '⌧',
_("KEYBOARD"): '⌨',
_("ERASE TO THE LEFT"): '⌫',
_("LEFT-POINTING ANGLE BRACKET"): '〈',
_("RIGHT-POINTING ANGLE BRACKET"): '〉',
_("BENZENE RING"): '⌬',
_("BENZENE RING WITH CIRCLE"): '⏣',
_("SYMMETRY"): '⌯',
_("TOTAL RUNOUT"): '⌰',
_("DIMENSION ORIGIN"): '⌱',
_("CONICAL TAPER"): '⌲',
_("SLOPE"): '⌳',
_("COUNTERBORE"): '⌴',
_("APL FUNCTIONAL SYMBOL SQUISH QUAD"): '⌷',
_("APL FUNCTIONAL SYMBOL QUAD EQUAL"): '⌸',
_("APL FUNCTIONAL SYMBOL QUAD DIVIDE"): '⌹',
_("APL FUNCTIONAL SYMBOL QUAD DIAMOND"): '⌺',
_("APL FUNCTIONAL SYMBOL QUAD JOT"): '⌻',
_("APL FUNCTIONAL SYMBOL QUAD CIRCLE"): '⌼',
_("APL FUNCTIONAL SYMBOL CIRCLE STILE"): '⌽',
_("APL FUNCTIONAL SYMBOL CIRCLE JOT"): '⌾',
_("APL FUNCTIONAL SYMBOL SLASH BAR"): '⌿',
_("APL FUNCTIONAL SYMBOL BACKSLASH BAR"): '⍀',
_("APL FUNCTIONAL SYMBOL QUAD SLASH"): '⍁',
_("APL FUNCTIONAL SYMBOL QUAD BACKSLASH"): '⍂',
_("APL FUNCTIONAL SYMBOL QUAD LESS-THAN"): '⍃',
_("APL FUNCTIONAL SYMBOL QUAD REATER-THAN"): '⍄',
_("APL FUNCTIONAL SYMBOL LEFTWARDS VANE"): '⍅',
_("APL FUNCTIONAL SYMBOL RIGHTWARDS VANE"): '⍆',
_("APL FUNCTIONAL SYMBOL QUAD EFTWARDS ARROW"): '⍇',
_("APL FUNCTIONAL SYMBOL QUAD IGHTWARDS ARROW"): '⍈',
_("APL FUNCTIONAL SYMBOL CIRCLE BACKSLASH"): '⍉',
_("APL FUNCTIONAL SYMBOL DOWN TACK UNDERBAR"): '⍊',
_("APL FUNCTIONAL SYMBOL DELTA STILE"): '⍋',
_("APL FUNCTIONAL SYMBOL QUAD DOWN CARET"): '⍌',
_("APL FUNCTIONAL SYMBOL QUAD DELTA"): '⍍',
_("APL FUNCTIONAL SYMBOL DOWN TACK JOT"): '⍎',
_("APL FUNCTIONAL SYMBOL UPWARDS VANE"): '⍏',
_("APL FUNCTIONAL SYMBOL QUAD UPWARDS ARROW"): '⍐',
_("APL FUNCTIONAL SYMBOL UP TACK OVERBAR"): '⍑',
_("APL FUNCTIONAL SYMBOL DEL STILE"): '⍒',
_("APL FUNCTIONAL SYMBOL QUAD UP CARET"): '⍓',
_("APL FUNCTIONAL SYMBOL QUAD DEL"): '⍔',
_("APL FUNCTIONAL SYMBOL UP TACK JOT"): '⍕',
_("APL FUNCTIONAL SYMBOL DOWNWARDS VANE"): '⍖',
_("APL FUNCTIONAL SYMBOL QUAD DOWNWARDS ARROW"): '⍗',
_("APL FUNCTIONAL SYMBOL QUOTE UNDERBAR"): '⍘',
_("APL FUNCTIONAL SYMBOL DELTA UNDERBAR"): '⍙',
_("APL FUNCTIONAL SYMBOL DIAMOND UNDERBAR"): '⍚',
_("APL FUNCTIONAL SYMBOL JOT UNDERBAR"): '⍛',
_("APL FUNCTIONAL SYMBOL CIRCLE UNDERBAR"): '⍜',
_("APL FUNCTIONAL SYMBOL UP SHOE JOT"): '⍝',
_("APL FUNCTIONAL SYMBOL QUOTE QUAD"): '⍞',
_("APL FUNCTIONAL SYMBOL CIRCLE STAR"): '⍟',
_("APL FUNCTIONAL SYMBOL QUAD COLON"): '⍠',
_("APL FUNCTIONAL SYMBOL UP TACK DIAERESIS"): '⍡',
_("APL FUNCTIONAL SYMBOL DEL DIAERESIS"): '⍢',
_("APL FUNCTIONAL SYMBOL STAR DIAERESIS"): '⍣',
_("APL FUNCTIONAL SYMBOL JOT DIAERESIS"): '⍤',
_("APL FUNCTIONAL SYMBOL CIRCLE DIAERESIS"): '⍥',
_("APL FUNCTIONAL SYMBOL DOWN SHOE STILE"): '⍦',
_("APL FUNCTIONAL SYMBOL LEFT SHOE STILE"): '⍧',
_("APL FUNCTIONAL SYMBOL TILDE DIAERESIS"): '⍨',
_("APL FUNCTIONAL SYMBOL GREATER-THAN DIERESIS"): '⍩',
_("APL FUNCTIONAL SYMBOL COMMA BAR"): '⍪',
_("APL FUNCTIONAL SYMBOL DEL TILDE"): '⍫',
_("APL FUNCTIONAL SYMBOL ZILDE"): '⍬',
_("APL FUNCTIONAL SYMBOL STILE TILDE"): '⍭',
_("APL FUNCTIONAL SYMBOL SEMICOLON UNDERBAR"): '⍮',
_("APL FUNCTIONAL SYMBOL QUAD NOT EQUAL"): '⍯',
_("APL FUNCTIONAL SYMBOL QUAD QUESTION"): '⍰',
_("APL FUNCTIONAL SYMBOL DOWN CARET TILDE"): '⍱',
_("APL FUNCTIONAL SYMBOL UP CARET TILDE"): '⍲',
_("APL FUNCTIONAL SYMBOL IOTA"): '⍳',
_("APL FUNCTIONAL SYMBOL RHO"): '⍴',
_("APL FUNCTIONAL SYMBOL OMEGA"): '⍵',
_("APL FUNCTIONAL SYMBOL ALPHA UNDERBAR"): '⍶',
_("APL FUNCTIONAL SYMBOL EPSILON UNDERBAR"): '⍷',
_("APL FUNCTIONAL SYMBOL IOTA UNDERBAR"): '⍸',
_("APL FUNCTIONAL SYMBOL OMEGA UNDERBAR"): '⍹',
_("APL FUNCTIONAL SYMBOL ALPHA"): '⍺',
_("APL FUNCTIONAL SYMBOL QUAD"): '⎕',
_("NOT CHECK MARK"): '⍻',
_("SHOULDERED OPEN BOX"): '⍽',
_("BELL SYMBOL"): '⍾',
_("VERTICAL LINE WITH MIDDLE DOT"): '⍿',
_("INSERTION SYMBOL"): '⎀',
_("CONTINUOUS UNDERLINE SYMBOL"): '⎁',
_("DISCONTINUOUS UNDERLINE SYMBOL"): '⎂',
_("EMPHASIS SYMBOL"): '⎃',
_("COMPOSITION SYMBOL"): '⎄',
_("WHITE SQUARE WITH CENTRE VERTICAL LINE"): '⎅',
_("ENTER SYMBOL"): '⎆',
_("ALTERNATIVE KEY SYMBOL"): '⎇',
_("HELM SYMBOL"): '⎈',
_("CIRCLED HORIZONTAL BAR WITH NOTCH"): '⎉',
_("CIRCLED TRIANGLE DOWN"): '⎊',
_("BROKEN CIRCLE WITH NORTHWEST ARROW"): '⎋',
_("UNDO SYMBOL"): '⎌',
_("DECIMAL SEPARATOR KEY SYMBOL"): '⎖',
_("PREVIOUS PAGE"): '⎗',
_("NEXT PAGE"): '⎘',
_("PRINT SCREEN SYMBOL"): '⎙',
_("CLEAR SCREEN SYMBOL"): '⎚',
_("MONOSTABLE SYMBOL"): '⎍',
_("HYSTERESIS SYMBOL"): '⎎',
_("OPEN-CIRCUIT-OUTPUT H-TYPE SYMBOL"): '⎏',
_("OPEN-CIRCUIT-OUTPUT L-TYPE SYMBOL"): '⎐',
_("PASSIVE-PULL-DOWN-OUTPUT SYMBOL"): '⎑',
_("PASSIVE-PULL-UP-OUTPUT SYMBOL"): '⎒',
_("DIRECT CURRENT SYMBOL FORM TWO"): '⎓',
_("SOFTWARE-FUNCTION SYMBOL"): '⎔',
_("LEFT PARENTHESIS UPPER HOOK"): '⎛',
_("LEFT PARENTHESIS EXTENSION"): '⎜',
_("LEFT PARENTHESIS LOWER HOOK"): '⎝',
_("RIGHT PARENTHESIS UPPER HOOK"): '⎞',
_("RIGHT PARENTHESIS EXTENSION"): '⎟',
_("RIGHT PARENTHESIS LOWER HOOK"): '⎠',
_("LEFT SQUARE BRACKET UPPER CORNER"): '⎡',
_("LEFT SQUARE BRACKET EXTENSION"): '⎢',
_("LEFT SQUARE BRACKET LOWER CORNER"): '⎣',
_("RIGHT SQUARE BRACKET UPPER CORNER"): '⎤',
_("RIGHT SQUARE BRACKET EXTENSION"): '⎥',
_("RIGHT SQUARE BRACKET LOWER CORNER"): '⎦',
_("LEFT CURLY BRACKET UPPER HOOK"): '⎧',
_("LEFT CURLY BRACKET MIDDLE PIECE"): '⎨',
_("LEFT CURLY BRACKET LOWER HOOK"): '⎩',
_("CURLY BRACKET EXTENSION"): '⎪',
_("RIGHT CURLY BRACKET UPPER HOOK"): '⎫',
_("RIGHT CURLY BRACKET MIDDLE PIECE"): '⎬',
_("RIGHT CURLY BRACKET LOWER HOOK"): '⎭',
_("UPPER LEFT OR LOWER RIGHT CURLY BRACKET SECTION"): '⎰',
_("UPPER RIGHT OR LOWER LEFT CURLY BRACKET SECTION"): '⎱',
_("INTEGRAL EXTENSION"): '⎮',
_("HORIZONTAL LINE EXTENSION"): '⎯',
_("VERTICAL LINE EXTENSION"): '⏐',
_("SUMMATION BOTTOM"): '⎳',
_("TOP SQUARE BRACKET"): '⎴',
_("BOTTOM SQUARE BRACKET"): '⎵',
_("BOTTOM SQUARE BRACKET OVER TOP SQUARE BRACKET"): '⎶',
_("TOP PARENTHESIS"): '⏜',
_("BOTTOM PARENTHESIS"): '⏝',
_("TOP CURLY BRACKET"): '⏞',
_("BOTTOM CURLY BRACKET"): '⏟',
_("TOP TORTOISE SHELL BRACKET"): '⏠',
_("BOTTOM TORTOISE SHELL BRACKET"): '⏡',
_("RADICAL SYMBOL BOTTOM"): '⎷',
_("LEFT VERTICAL BOX LINE"): '⎸',
_("RIGHT VERTICAL BOX LINE"): '⎹',
_("HORIZONTAL SCAN LINE-1"): '⎺',
_("HORIZONTAL SCAN LINE-3"): '⎻',
_("HORIZONTAL SCAN LINE-7"): '⎼',
_("HORIZONTAL SCAN LINE-9"): '⎽',
_("DENTISTRY SYMBOL LIGHT VERTICAL AND BOTTOM RIGHT"): '⎿',
_("DENTISTRY SYMBOL LIGHT VERTICAL WITH CIRCLE"): '⏀',
_("DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL WITH CIRCLE"): '⏁',
_("DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL WITH CIRCLE"): '⏂',
_("DENTISTRY SYMBOL LIGHT VERTICAL WITH TRIANGLE"): '⏃',
_("DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL WITH TRIANGLE"): '⏄',
_("DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL WITH TRIANGLE"): '⏅',
_("DENTISTRY SYMBOL LIGHT VERTICAL AND WAVE"): '⏆',
_("DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL WITH WAVE"): '⏇',
_("DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL WITH WAVE"): '⏈',
_("DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL"): '⏉',
_("DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL"): '⏊',
_("DENTISTRY SYMBOL LIGHT VERTICAL AND TOP LEFT"): '⏋',
_("DENTISTRY SYMBOL LIGHT VERTICAL AND BOTTOM LEFT"): '⏌',
_("RETURN SYMBOL"): '⏎',
_("EJECT SYMBOL"): '⏏',
_("METRICAL LONG OVER SHORT"): '⏒',
_("METRICAL SHORT OVER LONG"): '⏓',
_("METRICAL LONG OVER TWO SHORTS"): '⏔',
_("METRICAL TWO SHORTS OVER LONG"): '⏕',
_("METRICAL TWO SHORTS JOINED"): '⏖',
_("METRICAL TRISEME"): '⏗',
_("METRICAL TETRASEME"): '⏘',
_("METRICAL PENTASEME"): '⏙',
_("EARTH GROUND"): '⏚',
_("FUSE"): '⏛',
_("A Umlaut Capital"): 'Ä',
_("A Umlaut"): 'ä',
_("A Acute Capital"): 'Á',
_("A Acute"): 'á',
_("A Breve Capital"): 'Ă',
_("A Breve"): 'ă',
_("A circumflex Capital"): 'Â',
_("A circumflex"): 'â',
_("A Grave Capital"): 'À',
_("A Grave"): 'à',
_("A Macron Capital"): 'Ā',
_("A Macron"): 'ā',
_("A ogonek Capital"): 'Ą',
_("A ogonek"): 'ą',
_("A Tilde Capital"): 'Ã',
_("A Tilde"): 'ã',
_("A Ring Capital"): 'Å',
_("A Ring"): 'å',
_("B Hook Capital"): 'Ɓ',
_("B Hook"): 'ɓ',
_("C Acute Capital"): 'Ć',
_("C Acute"): 'ć',
_("C diaeresis Capital"): 'C̈',
_("C diaeresis"): 'c̈',
_("Capital C with dot above"): 'Ċ',
_("C with dot above"): 'ċ',
_("C hatchek Capital"): 'Č',
_("C hatchek"): 'č',
_("C cedilla Capital"): 'Ç',
_("C cedilla"): 'ç',
_("C circumflex Capital"): 'Ĉ',
_("C circumflex"): 'ĉ',
_("D hatchek Capital"): 'Ď',
_("D hatchek"): 'ď',
_("D Hook Capital"): 'Ɗ',
_("D Hook"): 'ɗ',
_("D Stroke Capital"): 'Đ',
_("D Stroke"): 'đ',
_("Capital D with Comma"): 'D̦',
_("D with Comma"): 'd̦',
_("Dotless j"): 'ȷ',
_("Copyright"): '©',
_("E hatchek Capital"): 'Ě',
_("E hatchek"): 'ě',
_("E ogonek Capital"): 'Ę',
_("E ogonek"): 'ę',
_("Ligature A E"): 'æ',
_("Capital E with Stroke"): 'Ɇ',
_("E with Stroke"): 'ɇ',
_("E Acute Capital"): 'É',
_("E Acute"): 'é',
_("Yen"): '¥',
_("Cents"): '¢',
_("Dong Sign"): '₫',
_("Euros"): '€',
_("Pound"): '£',
_("Peso"): '₱',
_("Ophiuchus"): '⛎',
_("Alpha"): 'α',
_("Nu Capital"): 'Ν',
_("Nu"): 'ν',
_("Beta Capital"): 'Β',
_("Beta"): 'β',
_("Xi Capital"): 'Ξ',
_("Xi"): 'ξ',
_("Gamma Capital"): 'Γ',
_("Gamma"): 'γ',
_("Omicron Capital"): 'Ο',
_("Omicron"): 'ο',
_("Delta Capital"): 'Δ',
_("Delta"): 'δ',
_("Pi Capitl"): 'Π',
_("Pi"): 'π',
_("Epsilon Capital"): 'Ε',
_("Epsilon"): 'ε',
_("Rho Capital"): 'Ρ',
_("Rho"): 'ρ',
_("Zeta Capital"): 'Ζ',
_("Zeta"): 'ζ',
_("Sigma Capital"): 'Σ',
_("Sigma"): 'σ',
_("Eta Capital"): 'Η',
_("Eta"): 'η',
_("Tau Capital"): 'Τ',
_("Tau"): 'τ',
_("Theta Capital"): 'Θ',
_("Theta"): 'θ',
_("Upsilon Capital"): 'Υ',
_("Upsilon"): 'υ',
_("Iota Capital"): 'Ι',
_("Iota"): 'ι',
_("Phi Capital"): 'Φ',
_("Phi"): 'φ',
_("Cappa Capital"): 'Κ',
_("Cappa"): 'κ',
_("Chi Capital"): 'Χ',
_("Chi"): 'χ',
_("Lambda Capital"): 'Λ',
_("Lambda"): 'λ',
_("Psi Capital"): 'Ψ',
_("Psi"): 'ψ',
_("Mu Capital"): 'Μ',
_("Mu"): 'μ',
_("Omega Capital"): 'Ω',
_("Omega"): 'ω',
_("E Circumflex Capital"): 'Ê',
_("E Circumflex"): 'ê',
_("E Grave Capital"): 'È',
_("E Grave"): 'è',
_("E Umlaut Capital"): 'Ë',
_("E Umlaut"): 'ë',
_("Capital E with Dot Above"): 'Ė',
_("E with Dot Above"): 'ė',
_("Capital G with Dot Above"): 'Ġ',
_("G with Dot Above"): 'ġ',
_("G Breve Capital"): 'Ğ',
_("G Breve"): 'ğ',
_("G Circumflex Capital"): 'Ĝ',
_("G Circumflex"): 'ĝ',
_("G Hook Capital"): 'Ɠ',
_("G Hook"): 'ɠ',
_("Capital G with Stroke"): 'Ǥ',
_("G with Stroke"): 'ǥ',
_("H Circumflex Capital"): 'Ĥ',
_("H Circumflex"): 'ĥ',
_("I Bar Capital"): 'Ɨ',
_("I Bar"): 'ɨ',
_("I Acute Capital"): 'Í',
_("I Acute"): 'í',
_("I Circumflex Capital"): 'Î',
_("I Circumflex"): 'î',
_("I Umlaut Capital"): 'Ï',
_("I Umlaut"): 'ï',
_("Turned M"): 'ɯ',
_("I Grave Capital"): 'Ì',
_("I Grave"): 'ì',
_("O Stroke"): 'ø',
_("O Stroke Capital"): 'Ø',
_("J with Stroke Capital"): 'Ɉ',
_("J with Stroke"): 'ɉ',
_("J Circumflex Capital"): 'Ĵ',
_("J Circumflex"): 'ĵ',
_("L Hatchek Capital"): 'Ľ',
_("L Hatchek"): 'ľ',
_("L Stroke Capital"): 'Ł',
_("L Stroke"): 'ł',
_("N Hatchek Capital"): 'Ň',
_("N Hatchek"): 'ň',
_("N Tilde Capital"): 'Ñ',
_("N Tilde"): 'ñ',
_("N Acute Capital"): 'Ń',
_("N Acute"): 'ń',
_("O Umlaut Capital"): 'Ö',
_("O Umlaut"): 'ö',
_("O Acute Capital"): 'Ó',
_("O Acute"): 'ó',
_("O Grave Capital"): 'Ò',
_("O Grave"): 'ò',
_("O Tilde Capital"): 'Õ',
_("O Tilde"): 'õ',
_("R Acute Capital"): 'Ŕ',
_("R Acute"): 'ŕ',
_("R Hatchek Capital"): 'Ř',
_("R Hatchek"): 'ř',
_("S Hatchek Capital"): 'Š',
_("S Hatchek"): 'š',
_("S Acute Capital"): 'Ś',
_("S Acute"): 'ś',
_("S Circumflex Capital"): 'Ŝ',
_("S Circumflex"): 'ŝ',
}

def terminate(self):
	global Symbols
	del Symbols